import type { BibleBook, CanonDivision } from "@/domain/content/types";

type TestamentLabel = "Old Testament" | "New Testament" | "Deuterocanon";

export type CanonEntry = {
  slug: string;
  name: string;
  shortName: string;
  canonDivision: CanonDivision;
  testamentLabel: TestamentLabel;
  chapterCount: number;
  order: number;
  osisCodes: string[];
  aliases: string[];
  rsvBookNumber?: number;
  greekTxtHeaders?: string[];
  brentonTitles?: string[];
  eobTitles?: string[];
  byzFilePrefixes?: string[];
  uanFilePrefixes?: string[];
};

type CanonSeed = Omit<CanonEntry, "aliases" | "osisCodes"> & {
  aliases?: string[];
  osisCodes?: string[];
};

const ORDINAL_WORDS = ["", "First", "Second", "Third", "Fourth"] as const;
const ORDINAL_ROMAN = ["", "I", "II", "III", "IV"] as const;

function normalizeAlias(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/gi, " ")
    .trim()
    .replace(/\s+/g, " ")
    .toLowerCase();
}

function unique(values: Array<string | undefined>) {
  return Array.from(
    new Set(values.filter((value): value is string => Boolean(value)).map((value) => value.trim())),
  );
}

function ordinalAliases(number: 1 | 2 | 3 | 4, title: string, shortTitle?: string) {
  const word = ORDINAL_WORDS[number];
  const roman = ORDINAL_ROMAN[number];

  return unique([
    `${number} ${title}`,
    `${roman} ${title}`,
    `${word} ${title}`,
    shortTitle ? `${number} ${shortTitle}` : undefined,
    shortTitle ? `${roman} ${shortTitle}` : undefined,
    shortTitle ? `${word} ${shortTitle}` : undefined,
  ]);
}

function book(seed: CanonSeed): CanonEntry {
  return {
    ...seed,
    osisCodes: unique([seed.slug, ...(seed.osisCodes ?? [])]),
    aliases: unique([seed.name, seed.shortName, ...(seed.aliases ?? [])]),
  };
}

const OT_BOOKS: CanonEntry[] = [
  book({
    slug: "genesis",
    name: "Genesis",
    shortName: "Gen",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 50,
    order: 1,
    osisCodes: ["Gen"],
    rsvBookNumber: 1,
    greekTxtHeaders: ["GENESIS"],
    brentonTitles: ["GENESIS"],
    aliases: ["Gn"],
  }),
  book({
    slug: "exodus",
    name: "Exodus",
    shortName: "Exod",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 40,
    order: 2,
    osisCodes: ["Exod", "Exo"],
    rsvBookNumber: 2,
    greekTxtHeaders: ["EXODUS"],
    brentonTitles: ["EXODUS"],
    aliases: ["Ex"],
  }),
  book({
    slug: "leviticus",
    name: "Leviticus",
    shortName: "Lev",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 27,
    order: 3,
    osisCodes: ["Lev"],
    rsvBookNumber: 3,
    greekTxtHeaders: ["LEVITICUS"],
    brentonTitles: ["LEVITICUS"],
  }),
  book({
    slug: "numbers",
    name: "Numbers",
    shortName: "Num",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 36,
    order: 4,
    osisCodes: ["Num"],
    rsvBookNumber: 4,
    greekTxtHeaders: ["NUMBERS"],
    brentonTitles: ["NUMBERS"],
  }),
  book({
    slug: "deuteronomy",
    name: "Deuteronomy",
    shortName: "Deut",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 34,
    order: 5,
    osisCodes: ["Deut", "Deu"],
    rsvBookNumber: 5,
    greekTxtHeaders: ["DEUTERONOMY"],
    brentonTitles: ["DEUTERONOMY"],
    aliases: ["Dt"],
  }),
  book({
    slug: "joshua",
    name: "Joshua",
    shortName: "Josh",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 24,
    order: 6,
    osisCodes: ["Josh"],
    rsvBookNumber: 6,
    greekTxtHeaders: ["JOSHUA", "JOS"],
    brentonTitles: ["JOSHUA"],
    aliases: ["Jos"],
  }),
  book({
    slug: "judges",
    name: "Judges",
    shortName: "Judg",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 21,
    order: 7,
    osisCodes: ["Judg", "Jdg"],
    rsvBookNumber: 7,
    greekTxtHeaders: ["JUDGES", "JDG"],
    brentonTitles: ["JUDGES"],
  }),
  book({
    slug: "ruth",
    name: "Ruth",
    shortName: "Ruth",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 4,
    order: 8,
    osisCodes: ["Ruth"],
    rsvBookNumber: 8,
    greekTxtHeaders: ["RUTH"],
    brentonTitles: ["RUTH"],
  }),
  book({
    slug: "first-samuel",
    name: "1 Samuel",
    shortName: "1 Sam",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 31,
    order: 9,
    osisCodes: ["1Sam"],
    rsvBookNumber: 9,
    brentonTitles: ["KINGS I", "1 SAMUEL"],
    aliases: [...ordinalAliases(1, "Samuel", "Sam"), "Kings I"],
  }),
  book({
    slug: "second-samuel",
    name: "2 Samuel",
    shortName: "2 Sam",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 24,
    order: 10,
    osisCodes: ["2Sam"],
    rsvBookNumber: 10,
    brentonTitles: ["KINGS II", "2 SAMUEL"],
    aliases: [...ordinalAliases(2, "Samuel", "Sam"), "Kings II"],
  }),
  book({
    slug: "first-kings",
    name: "1 Kings",
    shortName: "1 Kgs",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 22,
    order: 11,
    osisCodes: ["1Kgs", "1Kin"],
    rsvBookNumber: 11,
    brentonTitles: ["KINGS III", "1 KINGS"],
    aliases: [...ordinalAliases(1, "Kings", "Kgs"), "Kings III"],
  }),
  book({
    slug: "second-kings",
    name: "2 Kings",
    shortName: "2 Kgs",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 25,
    order: 12,
    osisCodes: ["2Kgs", "2Kin"],
    rsvBookNumber: 12,
    brentonTitles: ["KINGS IV", "2 KINGS"],
    aliases: [...ordinalAliases(2, "Kings", "Kgs"), "Kings IV"],
  }),
  book({
    slug: "first-chronicles",
    name: "1 Chronicles",
    shortName: "1 Chr",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 29,
    order: 13,
    osisCodes: ["1Chr"],
    rsvBookNumber: 13,
    brentonTitles: ["CHRONICLES I", "1 CHRONICLES"],
    aliases: [...ordinalAliases(1, "Chronicles", "Chr"), "Chronicles I"],
  }),
  book({
    slug: "second-chronicles",
    name: "2 Chronicles",
    shortName: "2 Chr",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 36,
    order: 14,
    osisCodes: ["2Chr"],
    rsvBookNumber: 14,
    brentonTitles: ["CHRONICLES II", "2 CHRONICLES"],
    aliases: [...ordinalAliases(2, "Chronicles", "Chr"), "Chronicles II"],
  }),
  book({
    slug: "ezra",
    name: "Ezra",
    shortName: "Ezra",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 10,
    order: 15,
    osisCodes: ["Ezra"],
    rsvBookNumber: 15,
    greekTxtHeaders: ["EZRA"],
    brentonTitles: ["EZRA"],
  }),
  book({
    slug: "nehemiah",
    name: "Nehemiah",
    shortName: "Neh",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 13,
    order: 16,
    osisCodes: ["Neh"],
    rsvBookNumber: 16,
    greekTxtHeaders: ["NEHEMIAH"],
    brentonTitles: ["NEHEMIAH"],
  }),
  book({
    slug: "esther",
    name: "Esther",
    shortName: "Esth",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 10,
    order: 17,
    osisCodes: ["Esth", "Esther"],
    rsvBookNumber: 17,
    greekTxtHeaders: ["ESTHER"],
    brentonTitles: ["ESTHER"],
  }),
  book({
    slug: "job",
    name: "Job",
    shortName: "Job",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 42,
    order: 18,
    osisCodes: ["Job"],
    rsvBookNumber: 18,
    greekTxtHeaders: ["JOB"],
    brentonTitles: ["JOB"],
  }),
  book({
    slug: "psalms",
    name: "Psalms",
    shortName: "Ps",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 150,
    order: 19,
    osisCodes: ["Ps", "Psa"],
    rsvBookNumber: 19,
    greekTxtHeaders: ["PSALMS"],
    brentonTitles: ["PSALMS"],
    aliases: ["Psalm"],
  }),
  book({
    slug: "proverbs",
    name: "Proverbs",
    shortName: "Prov",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 31,
    order: 20,
    osisCodes: ["Prov", "Pro"],
    rsvBookNumber: 20,
    greekTxtHeaders: ["PROVERBS"],
    brentonTitles: ["PROVERBS"],
  }),
  book({
    slug: "ecclesiastes",
    name: "Ecclesiastes",
    shortName: "Eccl",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 12,
    order: 21,
    osisCodes: ["Eccl", "Eccles"],
    rsvBookNumber: 21,
    greekTxtHeaders: ["ECCLESIASTES"],
    brentonTitles: ["ECCLESIASTES"],
    aliases: ["Qoheleth"],
  }),
  book({
    slug: "song-of-solomon",
    name: "Song of Solomon",
    shortName: "Song",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 8,
    order: 22,
    osisCodes: ["Song"],
    rsvBookNumber: 22,
    greekTxtHeaders: ["SON", "SONG"],
    brentonTitles: ["SONG OF SOLOMON", "SONG OF SONGS"],
    aliases: ["Canticles", "Song of Songs"],
  }),
  book({
    slug: "isaiah",
    name: "Isaiah",
    shortName: "Isa",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 66,
    order: 23,
    osisCodes: ["Isa"],
    rsvBookNumber: 23,
    greekTxtHeaders: ["ISAIAH"],
    brentonTitles: ["ISAIAH", "ESAIAS"],
    aliases: ["Esaias"],
  }),
  book({
    slug: "jeremiah",
    name: "Jeremiah",
    shortName: "Jer",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 52,
    order: 24,
    osisCodes: ["Jer"],
    rsvBookNumber: 24,
    greekTxtHeaders: ["JEREMIAH"],
    brentonTitles: ["JEREMIAH", "JEREMIAS"],
    aliases: ["Jeremias"],
  }),
  book({
    slug: "lamentations",
    name: "Lamentations",
    shortName: "Lam",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 5,
    order: 25,
    osisCodes: ["Lam"],
    rsvBookNumber: 25,
    greekTxtHeaders: ["LAMENTATIONS"],
    brentonTitles: ["LAMENTATIONS"],
  }),
  book({
    slug: "ezekiel",
    name: "Ezekiel",
    shortName: "Ezek",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 48,
    order: 26,
    osisCodes: ["Ezek", "Ezekiel"],
    rsvBookNumber: 26,
    greekTxtHeaders: ["EZE", "EZEKIEL"],
    brentonTitles: ["EZEKIEL", "JEZEKIEL"],
    aliases: ["Jezekiel"],
  }),
  book({
    slug: "daniel",
    name: "Daniel",
    shortName: "Dan",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 12,
    order: 27,
    osisCodes: ["Dan", "Daniel"],
    rsvBookNumber: 27,
    greekTxtHeaders: ["DANIEL"],
    brentonTitles: ["DANIEL"],
  }),
  book({
    slug: "hosea",
    name: "Hosea",
    shortName: "Hos",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 14,
    order: 28,
    osisCodes: ["Hos"],
    rsvBookNumber: 28,
    greekTxtHeaders: ["HOSEA", "OSEE"],
    brentonTitles: ["HOSEA", "OSEE"],
    aliases: ["Osee"],
  }),
  book({
    slug: "joel",
    name: "Joel",
    shortName: "Joel",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 3,
    order: 29,
    osisCodes: ["Joel"],
    rsvBookNumber: 29,
    greekTxtHeaders: ["JOEL", "JOE"],
    brentonTitles: ["JOEL"],
  }),
  book({
    slug: "amos",
    name: "Amos",
    shortName: "Amos",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 9,
    order: 30,
    osisCodes: ["Amos"],
    rsvBookNumber: 30,
    greekTxtHeaders: ["AMOS"],
    brentonTitles: ["AMOS"],
  }),
  book({
    slug: "obadiah",
    name: "Obadiah",
    shortName: "Obad",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 1,
    order: 31,
    osisCodes: ["Obad"],
    rsvBookNumber: 31,
    greekTxtHeaders: ["OBADIAH"],
    brentonTitles: ["OBADIAH", "OBDIAS"],
    aliases: ["Obdias"],
  }),
  book({
    slug: "jonah",
    name: "Jonah",
    shortName: "Jonah",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 4,
    order: 32,
    osisCodes: ["Jonah"],
    rsvBookNumber: 32,
    greekTxtHeaders: ["JONAH"],
    brentonTitles: ["JONAH", "JONAS"],
    aliases: ["Jonas"],
  }),
  book({
    slug: "micah",
    name: "Micah",
    shortName: "Mic",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 7,
    order: 33,
    osisCodes: ["Mic"],
    rsvBookNumber: 33,
    greekTxtHeaders: ["MICAH"],
    brentonTitles: ["MICAH", "MICHAEAS"],
    aliases: ["Michaeas"],
  }),
  book({
    slug: "nahum",
    name: "Nahum",
    shortName: "Nah",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 3,
    order: 34,
    osisCodes: ["Nah"],
    rsvBookNumber: 34,
    greekTxtHeaders: ["NAH", "NAHUM"],
    brentonTitles: ["NAHUM", "NAUM"],
    aliases: ["Naum"],
  }),
  book({
    slug: "habakkuk",
    name: "Habakkuk",
    shortName: "Hab",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 3,
    order: 35,
    osisCodes: ["Hab"],
    rsvBookNumber: 35,
    greekTxtHeaders: ["HABAKKUK"],
    brentonTitles: ["HABAKKUK", "AMBACUM"],
    aliases: ["Ambacum"],
  }),
  book({
    slug: "zephaniah",
    name: "Zephaniah",
    shortName: "Zeph",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 3,
    order: 36,
    osisCodes: ["Zeph"],
    rsvBookNumber: 36,
    greekTxtHeaders: ["ZEPHANIAH"],
    brentonTitles: ["ZEPHANIAH", "SOPHONIAS"],
    aliases: ["Sophonias"],
  }),
  book({
    slug: "haggai",
    name: "Haggai",
    shortName: "Hag",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 2,
    order: 37,
    osisCodes: ["Hag"],
    rsvBookNumber: 37,
    greekTxtHeaders: ["HAGGAI"],
    brentonTitles: ["HAGGAI", "AGGAEUS"],
    aliases: ["Aggaeus"],
  }),
  book({
    slug: "zechariah",
    name: "Zechariah",
    shortName: "Zech",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 14,
    order: 38,
    osisCodes: ["Zech", "Zec"],
    rsvBookNumber: 38,
    greekTxtHeaders: ["ZECHARIAH"],
    brentonTitles: ["ZECHARIAH", "ZACHARIAS"],
    aliases: ["Zacharias"],
  }),
  book({
    slug: "malachi",
    name: "Malachi",
    shortName: "Mal",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 4,
    order: 39,
    osisCodes: ["Mal"],
    rsvBookNumber: 39,
    greekTxtHeaders: ["MALACHI"],
    brentonTitles: ["MALACHI", "MALACHIAS"],
    aliases: ["Malachias"],
  }),
];

const DEUTEROCANON_BOOKS: CanonEntry[] = [
  book({
    slug: "first-esdras",
    name: "1 Esdras",
    shortName: "1 Esd",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 9,
    order: 40,
    osisCodes: ["1Esd"],
    brentonTitles: ["ESDRAS I", "1 ESDRAS"],
    aliases: [...ordinalAliases(1, "Esdras", "Esd"), "Esdras I"],
  }),
  book({
    slug: "second-esdras",
    name: "2 Esdras",
    shortName: "2 Esd",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 16,
    order: 41,
    osisCodes: ["2Esd"],
    aliases: [...ordinalAliases(2, "Esdras", "Esd"), "4 Ezra", "Second Ezra"],
  }),
  book({
    slug: "tobit",
    name: "Tobit",
    shortName: "Tob",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 14,
    order: 42,
    osisCodes: ["Tob"],
    brentonTitles: ["TOBIT"],
  }),
  book({
    slug: "judith",
    name: "Judith",
    shortName: "Jdt",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 16,
    order: 43,
    osisCodes: ["Jdt"],
    brentonTitles: ["JUDITH"],
  }),
  book({
    slug: "esther-greek",
    name: "Esther (Greek)",
    shortName: "Esth Gr",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 16,
    order: 44,
    osisCodes: ["AddEsth"],
    aliases: ["Greek Esther", "Additions to Esther", "Esther Greek"],
  }),
  book({
    slug: "wisdom",
    name: "Wisdom of Solomon",
    shortName: "Wis",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 19,
    order: 45,
    osisCodes: ["Wis"],
    brentonTitles: ["WISDOM OF SOLOMON"],
    aliases: ["Wisdom"],
  }),
  book({
    slug: "sirach",
    name: "Sirach",
    shortName: "Sir",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 51,
    order: 46,
    osisCodes: ["Sir"],
    brentonTitles: ["SIRACH", "ECCLESIASTICUS"],
    aliases: ["Ecclesiasticus", "Wisdom of Sirach"],
  }),
  book({
    slug: "baruch",
    name: "Baruch",
    shortName: "Bar",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 5,
    order: 47,
    osisCodes: ["Bar"],
    brentonTitles: ["BARUCH"],
  }),
  book({
    slug: "epistle-of-jeremiah",
    name: "Epistle of Jeremiah",
    shortName: "Ep Jer",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 1,
    order: 48,
    osisCodes: ["EpJer"],
    brentonTitles: ["EPISTLE OF JEREMY", "LETTER OF JEREMIAH"],
    aliases: ["Epistle of Jeremy", "Letter of Jeremiah"],
  }),
  book({
    slug: "prayer-of-azariah",
    name: "Prayer of Azariah",
    shortName: "Pr Azar",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 1,
    order: 49,
    osisCodes: ["PrAzar", "AddDan"],
    aliases: [
      "Song of the Three Children",
      "Song of the Three Holy Children",
      "Prayer of Azarias",
      "Prayer of Azariah and the Song of the Three Holy Children",
    ],
  }),
  book({
    slug: "susanna",
    name: "Susanna",
    shortName: "Sus",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 1,
    order: 50,
    osisCodes: ["Sus"],
    brentonTitles: ["SUSANNA"],
  }),
  book({
    slug: "bel-and-the-dragon",
    name: "Bel and the Dragon",
    shortName: "Bel",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 1,
    order: 51,
    osisCodes: ["Bel", "BelTh"],
    brentonTitles: ["BEL AND THE DRAGON"],
    aliases: ["Bel"],
  }),
  book({
    slug: "prayer-of-manasseh",
    name: "Prayer of Manasseh",
    shortName: "Pr Man",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 1,
    order: 52,
    osisCodes: ["PrMan"],
    brentonTitles: ["PRAYER OF MANASSES", "PRAYER OF MANASSEH"],
    aliases: ["Prayer of Manasses"],
  }),
  book({
    slug: "first-maccabees",
    name: "1 Maccabees",
    shortName: "1 Macc",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 16,
    order: 53,
    osisCodes: ["1Macc"],
    brentonTitles: ["MACCABEES I", "1 MACCABEES"],
    aliases: [...ordinalAliases(1, "Maccabees", "Macc"), "Maccabees I"],
  }),
  book({
    slug: "second-maccabees",
    name: "2 Maccabees",
    shortName: "2 Macc",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 15,
    order: 54,
    osisCodes: ["2Macc"],
    brentonTitles: ["MACCABEES II", "2 MACCABEES"],
    aliases: [...ordinalAliases(2, "Maccabees", "Macc"), "Maccabees II"],
  }),
  book({
    slug: "third-maccabees",
    name: "3 Maccabees",
    shortName: "3 Macc",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 7,
    order: 55,
    osisCodes: ["3Macc"],
    brentonTitles: ["MACCABEES III", "3 MACCABEES"],
    aliases: [...ordinalAliases(3, "Maccabees", "Macc"), "Maccabees III"],
  }),
  book({
    slug: "fourth-maccabees",
    name: "4 Maccabees",
    shortName: "4 Macc",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 18,
    order: 56,
    osisCodes: ["4Macc"],
    brentonTitles: ["MACCABEES IV", "4 MACCABEES"],
    aliases: [...ordinalAliases(4, "Maccabees", "Macc"), "Maccabees IV"],
  }),
  book({
    slug: "psalm-151",
    name: "Psalm 151",
    shortName: "Ps 151",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 1,
    order: 57,
    osisCodes: ["Ps151", "AddPs"],
    aliases: ["Psalm 151"],
  }),
];

const NT_BOOKS: CanonEntry[] = [
  book({
    slug: "matthew",
    name: "Matthew",
    shortName: "Matt",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 28,
    order: 58,
    osisCodes: ["Matt", "Mat"],
    rsvBookNumber: 40,
    greekTxtHeaders: ["MATTHEW"],
    eobTitles: ["ACCORDING TO MATTHEW", "MATTHEW"],
    byzFilePrefixes: ["MT"],
    uanFilePrefixes: ["MT"],
    aliases: ["Mt"],
  }),
  book({
    slug: "mark",
    name: "Mark",
    shortName: "Mark",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 16,
    order: 59,
    osisCodes: ["Mark", "Mar"],
    rsvBookNumber: 41,
    greekTxtHeaders: ["MARK", "MAR"],
    eobTitles: ["ACCORDING TO MARK", "MARK"],
    byzFilePrefixes: ["MR"],
    uanFilePrefixes: ["MR"],
    aliases: ["Mk"],
  }),
  book({
    slug: "luke",
    name: "Luke",
    shortName: "Luke",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 24,
    order: 60,
    osisCodes: ["Luke", "Luk"],
    rsvBookNumber: 42,
    greekTxtHeaders: ["LUKE"],
    eobTitles: ["ACCORDING TO LUKE", "LUKE"],
    byzFilePrefixes: ["LU"],
    uanFilePrefixes: ["LU"],
    aliases: ["Lk"],
  }),
  book({
    slug: "john",
    name: "John",
    shortName: "John",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 21,
    order: 61,
    osisCodes: ["John", "Joh"],
    rsvBookNumber: 43,
    greekTxtHeaders: ["JOHN", "JOH"],
    eobTitles: ["ACCORDING TO JOHN", "THE GOSPEL OF JOHN", "JOHN"],
    byzFilePrefixes: ["JOH"],
    uanFilePrefixes: ["JOH"],
    aliases: ["Jn", "Jhn"],
  }),
  book({
    slug: "acts",
    name: "Acts",
    shortName: "Acts",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 28,
    order: 62,
    osisCodes: ["Acts", "Act"],
    rsvBookNumber: 44,
    greekTxtHeaders: ["ACTS"],
    eobTitles: ["ACTS OF THE APOSTLES", "ACTS"],
    byzFilePrefixes: ["AC"],
    uanFilePrefixes: ["AC"],
  }),
  book({
    slug: "romans",
    name: "Romans",
    shortName: "Rom",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 16,
    order: 63,
    osisCodes: ["Rom"],
    rsvBookNumber: 45,
    greekTxtHeaders: ["ROMANS"],
    eobTitles: ["TO THE ROMANS", "ROMANS"],
    byzFilePrefixes: ["RO"],
    uanFilePrefixes: ["RO"],
  }),
  book({
    slug: "first-corinthians",
    name: "1 Corinthians",
    shortName: "1 Cor",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 16,
    order: 64,
    osisCodes: ["1Cor"],
    rsvBookNumber: 46,
    greekTxtHeaders: ["1 CORINTHIANS"],
    eobTitles: ["TO THE CORINTHIANS 1", "1 CORINTHIANS"],
    byzFilePrefixes: ["1CO"],
    uanFilePrefixes: ["1CO"],
    aliases: ordinalAliases(1, "Corinthians", "Cor"),
  }),
  book({
    slug: "second-corinthians",
    name: "2 Corinthians",
    shortName: "2 Cor",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 13,
    order: 65,
    osisCodes: ["2Cor"],
    rsvBookNumber: 47,
    greekTxtHeaders: ["2 CORINTHIANS"],
    eobTitles: ["TO THE CORINTHIANS 2", "2 CORINTHIANS"],
    byzFilePrefixes: ["2CO"],
    uanFilePrefixes: ["2CO"],
    aliases: ordinalAliases(2, "Corinthians", "Cor"),
  }),
  book({
    slug: "galatians",
    name: "Galatians",
    shortName: "Gal",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 6,
    order: 66,
    osisCodes: ["Gal"],
    rsvBookNumber: 48,
    greekTxtHeaders: ["GALATIANS"],
    eobTitles: ["TO THE GALATIANS", "GALATIANS"],
    byzFilePrefixes: ["GA"],
    uanFilePrefixes: ["GA"],
  }),
  book({
    slug: "ephesians",
    name: "Ephesians",
    shortName: "Eph",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 6,
    order: 67,
    osisCodes: ["Eph"],
    rsvBookNumber: 49,
    greekTxtHeaders: ["EPHESIANS"],
    eobTitles: ["TO THE EPHESIANS", "EPHESIANS"],
    byzFilePrefixes: ["EPH"],
    uanFilePrefixes: ["EPH"],
  }),
  book({
    slug: "philippians",
    name: "Philippians",
    shortName: "Phil",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 4,
    order: 68,
    osisCodes: ["Phil"],
    rsvBookNumber: 50,
    greekTxtHeaders: ["PHILIPPIANS", "PHI"],
    eobTitles: ["TO THE PHILIPPIANS", "PHILIPPIANS"],
    byzFilePrefixes: ["PHP"],
    uanFilePrefixes: ["PHP"],
  }),
  book({
    slug: "colossians",
    name: "Colossians",
    shortName: "Col",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 4,
    order: 69,
    osisCodes: ["Col"],
    rsvBookNumber: 51,
    greekTxtHeaders: ["COLOSSIANS"],
    eobTitles: ["TO THE COLOSSIANS", "COLOSSIANS"],
    byzFilePrefixes: ["COL"],
    uanFilePrefixes: ["COL"],
  }),
  book({
    slug: "first-thessalonians",
    name: "1 Thessalonians",
    shortName: "1 Thess",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 5,
    order: 70,
    osisCodes: ["1Thess", "1Thes"],
    rsvBookNumber: 52,
    greekTxtHeaders: ["1 THESSALONIANS"],
    eobTitles: ["TO THE THESSALONIANS 1", "1 THESSALONIANS"],
    byzFilePrefixes: ["1TH"],
    uanFilePrefixes: ["1TH"],
    aliases: ordinalAliases(1, "Thessalonians", "Thess"),
  }),
  book({
    slug: "second-thessalonians",
    name: "2 Thessalonians",
    shortName: "2 Thess",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 3,
    order: 71,
    osisCodes: ["2Thess", "2Thes"],
    rsvBookNumber: 53,
    greekTxtHeaders: ["2 THESSALONIANS"],
    eobTitles: ["TO THE THESSALONIANS 2", "2 THESSALONIANS"],
    byzFilePrefixes: ["2TH"],
    uanFilePrefixes: ["2TH"],
    aliases: ordinalAliases(2, "Thessalonians", "Thess"),
  }),
  book({
    slug: "first-timothy",
    name: "1 Timothy",
    shortName: "1 Tim",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 6,
    order: 72,
    osisCodes: ["1Tim"],
    rsvBookNumber: 54,
    greekTxtHeaders: ["1 TIMOTHY"],
    eobTitles: ["TO TIMOTHY 1", "1 TIMOTHY"],
    byzFilePrefixes: ["1TI"],
    uanFilePrefixes: ["1TI"],
    aliases: ordinalAliases(1, "Timothy", "Tim"),
  }),
  book({
    slug: "second-timothy",
    name: "2 Timothy",
    shortName: "2 Tim",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 4,
    order: 73,
    osisCodes: ["2Tim"],
    rsvBookNumber: 55,
    greekTxtHeaders: ["2 TIMOTHY"],
    eobTitles: ["TO TIMOTHY 2", "2 TIMOTHY"],
    byzFilePrefixes: ["2TI"],
    uanFilePrefixes: ["2TI"],
    aliases: ordinalAliases(2, "Timothy", "Tim"),
  }),
  book({
    slug: "titus",
    name: "Titus",
    shortName: "Titus",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 3,
    order: 74,
    osisCodes: ["Titus", "Tit"],
    rsvBookNumber: 56,
    greekTxtHeaders: ["TITUS"],
    eobTitles: ["TO TITUS", "TITUS"],
    byzFilePrefixes: ["TIT"],
    uanFilePrefixes: ["TIT"],
  }),
  book({
    slug: "philemon",
    name: "Philemon",
    shortName: "Phlm",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 1,
    order: 75,
    osisCodes: ["Phlm", "Philem"],
    rsvBookNumber: 57,
    greekTxtHeaders: ["PHILEMON"],
    eobTitles: ["TO PHILEMON", "PHILEMON"],
    byzFilePrefixes: ["PHM"],
    uanFilePrefixes: ["PHM"],
    aliases: ["Phm"],
  }),
  book({
    slug: "hebrews",
    name: "Hebrews",
    shortName: "Heb",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 13,
    order: 76,
    osisCodes: ["Heb"],
    rsvBookNumber: 58,
    greekTxtHeaders: ["HEBREWS"],
    eobTitles: ["TO THE HEBREWS", "HEBREWS"],
    byzFilePrefixes: ["HEB"],
    uanFilePrefixes: ["HEB"],
  }),
  book({
    slug: "james",
    name: "James",
    shortName: "Jas",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 5,
    order: 77,
    osisCodes: ["Jas", "James"],
    rsvBookNumber: 59,
    greekTxtHeaders: ["JAMES", "JAM"],
    eobTitles: ["JAMES"],
    byzFilePrefixes: ["JAS"],
    uanFilePrefixes: ["JAS"],
  }),
  book({
    slug: "first-peter",
    name: "1 Peter",
    shortName: "1 Pet",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 5,
    order: 78,
    osisCodes: ["1Pet"],
    rsvBookNumber: 60,
    greekTxtHeaders: ["1 PETER"],
    eobTitles: ["1 PETER"],
    byzFilePrefixes: ["1PE"],
    uanFilePrefixes: ["1PE"],
    aliases: ordinalAliases(1, "Peter", "Pet"),
  }),
  book({
    slug: "second-peter",
    name: "2 Peter",
    shortName: "2 Pet",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 3,
    order: 79,
    osisCodes: ["2Pet"],
    rsvBookNumber: 61,
    greekTxtHeaders: ["2 PETER"],
    eobTitles: ["2 PETER"],
    byzFilePrefixes: ["2PE"],
    uanFilePrefixes: ["2PE"],
    aliases: ordinalAliases(2, "Peter", "Pet"),
  }),
  book({
    slug: "first-john",
    name: "1 John",
    shortName: "1 John",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 5,
    order: 80,
    osisCodes: ["1John"],
    rsvBookNumber: 62,
    greekTxtHeaders: ["1 JOHN"],
    eobTitles: ["1 JOHN"],
    byzFilePrefixes: ["1JO"],
    uanFilePrefixes: ["1JO"],
    aliases: ordinalAliases(1, "John"),
  }),
  book({
    slug: "second-john",
    name: "2 John",
    shortName: "2 John",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 1,
    order: 81,
    osisCodes: ["2John"],
    rsvBookNumber: 63,
    greekTxtHeaders: ["2 JOHN"],
    eobTitles: ["2 JOHN"],
    byzFilePrefixes: ["2JO"],
    uanFilePrefixes: ["2JO"],
    aliases: ordinalAliases(2, "John"),
  }),
  book({
    slug: "third-john",
    name: "3 John",
    shortName: "3 John",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 1,
    order: 82,
    osisCodes: ["3John"],
    rsvBookNumber: 64,
    greekTxtHeaders: ["3 JOHN"],
    eobTitles: ["3 JOHN"],
    byzFilePrefixes: ["3JO"],
    uanFilePrefixes: ["3JO"],
    aliases: ordinalAliases(3, "John"),
  }),
  book({
    slug: "jude",
    name: "Jude",
    shortName: "Jude",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 1,
    order: 83,
    osisCodes: ["Jude"],
    rsvBookNumber: 65,
    greekTxtHeaders: ["JUDE"],
    eobTitles: ["JUDE"],
    byzFilePrefixes: ["JUDE"],
    uanFilePrefixes: ["JUDE"],
  }),
  book({
    slug: "revelation",
    name: "Revelation",
    shortName: "Rev",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 22,
    order: 84,
    osisCodes: ["Rev"],
    rsvBookNumber: 66,
    greekTxtHeaders: ["REVELATION"],
    eobTitles: ["REVELATION", "THE REVELATION OF JOHN"],
    byzFilePrefixes: ["RE"],
    uanFilePrefixes: ["RE"],
    aliases: ["Apocalypse"],
  }),
];

export const FULL_CANON = [...OT_BOOKS, ...DEUTEROCANON_BOOKS, ...NT_BOOKS];

const bySlug = new Map<string, CanonEntry>();
const byOsisCode = new Map<string, CanonEntry>();
const byRsvBookNumber = new Map<number, CanonEntry>();
const byAlias = new Map<string, CanonEntry>();
const byGreekHeader = new Map<string, CanonEntry>();
const byBrentonTitle = new Map<string, CanonEntry>();
const byEobTitle = new Map<string, CanonEntry>();
const byByzPrefix = new Map<string, CanonEntry>();
const byUanPrefix = new Map<string, CanonEntry>();

function registerAliases(map: Map<string, CanonEntry>, entry: CanonEntry, values: string[]) {
  for (const value of values) {
    map.set(normalizeAlias(value), entry);
  }
}

for (const entry of FULL_CANON) {
  bySlug.set(entry.slug, entry);

  for (const osisCode of entry.osisCodes) {
    byOsisCode.set(osisCode, entry);
  }

  if (typeof entry.rsvBookNumber === "number") {
    byRsvBookNumber.set(entry.rsvBookNumber, entry);
  }

  registerAliases(byAlias, entry, entry.aliases);
  registerAliases(byGreekHeader, entry, entry.greekTxtHeaders ?? []);
  registerAliases(byBrentonTitle, entry, entry.brentonTitles ?? []);
  registerAliases(byEobTitle, entry, entry.eobTitles ?? []);

  for (const prefix of entry.byzFilePrefixes ?? []) {
    byByzPrefix.set(prefix.toUpperCase(), entry);
  }

  for (const prefix of entry.uanFilePrefixes ?? []) {
    byUanPrefix.set(prefix.toUpperCase(), entry);
  }
}

export function canonEntryToBook(entry: CanonEntry): BibleBook {
  return {
    id: entry.slug,
    slug: entry.slug,
    name: entry.name,
    shortName: entry.shortName,
    canonDivision: entry.canonDivision,
    testamentLabel: entry.testamentLabel,
    chapterCount: entry.chapterCount,
    order: entry.order,
  };
}

export function getAllBooks() {
  return FULL_CANON.map(canonEntryToBook);
}

export function getCanonBySlug(slug: string) {
  return bySlug.get(slug);
}

export function getCanonByOsisCode(code: string) {
  return byOsisCode.get(code);
}

export function getCanonByRsvBookNumber(bookNumber: number) {
  return byRsvBookNumber.get(bookNumber);
}

export function getCanonByAlias(alias: string) {
  return byAlias.get(normalizeAlias(alias));
}

export function getCanonByGreekHeader(header: string) {
  return byGreekHeader.get(normalizeAlias(header));
}

export function getCanonByBrentonTitle(title: string) {
  return byBrentonTitle.get(normalizeAlias(title));
}

export function getCanonByEobTitle(title: string) {
  return byEobTitle.get(normalizeAlias(title));
}

export function getCanonByByzPrefix(prefix: string) {
  return byByzPrefix.get(prefix.toUpperCase());
}

export function getCanonByUanPrefix(prefix: string) {
  return byUanPrefix.get(prefix.toUpperCase());
}

export function getReferenceBookAliases() {
  return FULL_CANON.map((entry) => ({
    slug: entry.slug,
    name: entry.name,
    aliases: entry.aliases.map(normalizeAlias),
  }));
}

export function normalizeCanonAlias(value: string) {
  return normalizeAlias(value);
}
