import type {
  CommentaryEntry,
  Person,
  SourceRecord,
  TopicTag,
  Work,
  WorkSection,
} from "@/domain/content/types";
import { createChapterId, createReference, createVerseId } from "@/lib/content/reference";

export const sourceRecords: SourceRecord[] = [
  {
    id: "source-oca-daily",
    label: "Orthodox daily calendar sample",
    collection: "Orthodox source",
    sourceType: "orthodox-web",
    url: "https://www.oca.org/saints/lives",
    note: "Used as a prototype reference for daily commemoration structure.",
    isSeeded: true,
  },
  {
    id: "source-new-advent-john",
    label: "Homilies on the Gospel of John",
    collection: "New Advent",
    sourceType: "web-collection",
    url: "https://www.newadvent.org/fathers/",
    note: "Prototype source for verse-linked patristic commentary.",
    isSeeded: true,
  },
  {
    id: "source-ccel-hexaemeron",
    label: "Hexaemeron",
    collection: "CCEL",
    sourceType: "web-collection",
    url: "https://ccel.org/",
    note: "Prototype source for creation commentary and linked excerpts.",
    isSeeded: true,
  },
  {
    id: "source-public-pdf-anthology",
    label: "Public patristic PDF anthology",
    collection: "PDF archive",
    sourceType: "pdf",
    url: "https://archive.org/",
    note: "Represents future parsed PDF-based reading material.",
    isSeeded: true,
  },
];

export const topicTags: TopicTag[] = [
  {
    slug: "logos",
    label: "Logos",
    summary: "Christ as the eternal Word through whom creation and revelation are given.",
  },
  {
    slug: "incarnation",
    label: "Incarnation",
    summary: "The Word's taking flesh for the salvation and restoration of humanity.",
  },
  {
    slug: "theosis",
    label: "Theosis",
    summary: "Participation in divine life through union with Christ by grace.",
  },
  {
    slug: "light",
    label: "Divine Light",
    summary: "The scriptural and patristic language of illumination, revelation, and life.",
  },
  {
    slug: "creation",
    label: "Creation",
    summary: "The beginning of the world and its relation to the Word and divine wisdom.",
  },
];

export const people: Person[] = [
  {
    id: "john-chrysostom",
    slug: "john-chrysostom",
    name: "John Chrysostom",
    honorific: "St.",
    kind: "father",
    eraLabel: "4th century",
    summary: "Archbishop of Constantinople whose homilies combine doctrinal clarity with pastoral directness.",
    traditions: ["Antioch", "Constantinople"],
    topicSlugs: ["logos", "incarnation", "light"],
    featuredWorkIds: ["homilies-on-john"],
    feastDayLabel: "November 13",
  },
  {
    id: "cyril-of-alexandria",
    slug: "cyril-of-alexandria",
    name: "Cyril of Alexandria",
    honorific: "St.",
    kind: "father",
    eraLabel: "5th century",
    summary: "A major Christological voice whose commentary keeps the person of Christ at the center of exegesis.",
    traditions: ["Alexandria"],
    topicSlugs: ["logos", "incarnation"],
    featuredWorkIds: ["commentary-on-john"],
    feastDayLabel: "June 9",
  },
  {
    id: "basil-the-great",
    slug: "basil-the-great",
    name: "Basil the Great",
    honorific: "St.",
    kind: "father",
    eraLabel: "4th century",
    summary: "Bishop, ascetic, and preacher whose creation homilies remain a model of theological exposition.",
    traditions: ["Cappadocia"],
    topicSlugs: ["creation", "light"],
    featuredWorkIds: ["hexaemeron"],
    feastDayLabel: "January 1",
  },
  {
    id: "athanasius-the-great",
    slug: "athanasius-the-great",
    name: "Athanasius the Great",
    honorific: "St.",
    kind: "father",
    eraLabel: "4th century",
    summary: "Defender of Nicene faith whose soteriology anchors later Orthodox teaching on deification.",
    traditions: ["Alexandria"],
    topicSlugs: ["incarnation", "theosis"],
    featuredWorkIds: ["on-the-incarnation"],
    feastDayLabel: "January 18",
  },
  {
    id: "gregory-palamas",
    slug: "gregory-palamas",
    name: "Gregory Palamas",
    honorific: "St.",
    kind: "saint",
    eraLabel: "14th century",
    summary: "Archbishop of Thessalonica whose defense of uncreated grace shaped Orthodox teaching on participation in divine life.",
    traditions: ["Byzantine"],
    topicSlugs: ["theosis", "light"],
    featuredWorkIds: ["triads"],
    feastDayLabel: "Second Sunday of Great Lent",
  },
  {
    id: "theophylact-of-ohrid",
    slug: "theophylact-of-ohrid",
    name: "Theophylact of Ohrid",
    honorific: "Blessed",
    kind: "theologian",
    eraLabel: "11th century",
    summary: "A lucid commentator whose Gospel exegesis distills earlier Fathers into accessible interpretation.",
    traditions: ["Byzantine"],
    topicSlugs: ["logos", "incarnation"],
    featuredWorkIds: ["explanation-of-john"],
  },
  {
    id: "forty-martyrs-of-sebaste",
    slug: "forty-martyrs-of-sebaste",
    name: "The Forty Martyrs of Sebaste",
    honorific: "Holy",
    kind: "saint",
    eraLabel: "4th century",
    summary: "Roman soldiers martyred together after refusing to renounce Christ, remembered for steadfast confession and mutual courage.",
    traditions: ["Cappadocia"],
    topicSlugs: ["martyrdom", "perseverance"],
    featuredWorkIds: ["life-of-the-forty-martyrs"],
    feastDayLabel: "March 9",
  },
];

export const works: Work[] = [
  {
    id: "homilies-on-john",
    slug: "homilies-on-john",
    personId: "john-chrysostom",
    title: "Homilies on the Gospel of John",
    shortTitle: "Homilies on John",
    workType: "homily",
    lengthLabel: "long",
    eraLabel: "4th century",
    summary: "Chrysostom's preaching on John emphasizes the eternal Son, the Incarnation, and the moral stakes of belief.",
    topicSlugs: ["logos", "incarnation", "light"],
    sourceId: "source-new-advent-john",
    verseRefs: [createReference("john", "John", 1, 1, 18)],
  },
  {
    id: "commentary-on-john",
    slug: "commentary-on-john",
    personId: "cyril-of-alexandria",
    title: "Commentary on the Gospel of John",
    shortTitle: "Commentary on John",
    workType: "commentary",
    lengthLabel: "long",
    eraLabel: "5th century",
    summary: "Cyril reads John through the unity of Christ's person and the saving purpose of the Incarnation.",
    topicSlugs: ["logos", "incarnation"],
    sourceId: "source-new-advent-john",
    verseRefs: [createReference("john", "John", 1, 1, 18)],
  },
  {
    id: "hexaemeron",
    slug: "hexaemeron",
    personId: "basil-the-great",
    title: "Hexaemeron",
    shortTitle: "Hexaemeron",
    workType: "homily",
    lengthLabel: "medium",
    eraLabel: "4th century",
    summary: "Nine homilies on the six days of creation, attentive to theology, creation, and wonder.",
    topicSlugs: ["creation", "light"],
    sourceId: "source-ccel-hexaemeron",
    verseRefs: [createReference("genesis", "Genesis", 1, 1, 5)],
  },
  {
    id: "on-the-incarnation",
    slug: "on-the-incarnation",
    personId: "athanasius-the-great",
    title: "On the Incarnation",
    shortTitle: "On the Incarnation",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "4th century",
    summary: "Athanasius presents the saving descent of the Word and the restoration of humanity in Christ.",
    topicSlugs: ["incarnation", "theosis"],
    sourceId: "source-public-pdf-anthology",
    verseRefs: [
      createReference("john", "John", 1, 14),
      createReference("second-peter", "2 Peter", 1, 4),
    ],
  },
  {
    id: "triads",
    slug: "triads",
    personId: "gregory-palamas",
    title: "The Triads",
    shortTitle: "Triads",
    workType: "treatise",
    lengthLabel: "long",
    eraLabel: "14th century",
    summary: "Palamas articulates prayer, illumination, and participation in divine energies without confusion of essence.",
    topicSlugs: ["theosis", "light"],
    sourceId: "source-public-pdf-anthology",
    verseRefs: [
      createReference("second-peter", "2 Peter", 1, 4),
      createReference("john", "John", 1, 4),
    ],
  },
  {
    id: "explanation-of-john",
    slug: "explanation-of-john",
    personId: "theophylact-of-ohrid",
    title: "Explanation of the Holy Gospel According to John",
    shortTitle: "Explanation of John",
    workType: "commentary",
    lengthLabel: "medium",
    eraLabel: "11th century",
    summary: "A compact, readable synthesis of earlier Greek Fathers on the Johannine text.",
    topicSlugs: ["logos", "incarnation"],
    sourceId: "source-public-pdf-anthology",
    verseRefs: [createReference("john", "John", 1, 1, 18)],
  },
  {
    id: "life-of-the-forty-martyrs",
    slug: "life-of-the-forty-martyrs",
    personId: "forty-martyrs-of-sebaste",
    title: "Life of the Forty Martyrs of Sebaste",
    shortTitle: "Life of the Forty Martyrs",
    workType: "life",
    lengthLabel: "short",
    eraLabel: "4th century",
    summary: "The witness of the Forty Martyrs embodies endurance, mutual strengthening, and joy in Christ.",
    topicSlugs: ["martyrdom", "perseverance"],
    sourceId: "source-oca-daily",
    verseRefs: [],
  },
];

export const workSections: WorkSection[] = [
  {
    id: "section-athanasius-word-became-man",
    workId: "on-the-incarnation",
    label: "The Word became man for our healing",
    excerpt:
      "The Word takes what is ours so that our nature, renewed in Him, may be brought back to incorruption and communion with God.",
    sourceId: "source-public-pdf-anthology",
    verseRef: createReference("john", "John", 1, 14),
  },
  {
    id: "section-palamas-divine-light",
    workId: "triads",
    label: "Participation without confusion",
    excerpt:
      "Union with God is real and transformative, yet it is received as grace; the creature does not become the divine essence.",
    sourceId: "source-public-pdf-anthology",
    verseRef: createReference("second-peter", "2 Peter", 1, 4),
  },
  {
    id: "section-hexaemeron-beginning",
    workId: "hexaemeron",
    label: "The beginning of creation",
    excerpt:
      "The beginning does not place God inside time; it marks the first appearance of created order by His free will.",
    sourceId: "source-ccel-hexaemeron",
    verseRef: createReference("genesis", "Genesis", 1, 1),
  },
];

export const commentaryEntries: CommentaryEntry[] = [
  {
    id: "commentary-chrysostom-john-1-1",
    relation: "verse",
    targetVerseId: createVerseId("kjva", "john", 1, 1),
    topicSlugs: ["logos"],
    personId: "john-chrysostom",
    workId: "homilies-on-john",
    title: "John begins above time",
    excerpt:
      "The Evangelist does not begin with earth, genealogy, or earthly ministry, but carries the hearer immediately to the eternal being of the Only-Begotten.",
    takeaway:
      "The prologue protects Christ's divinity by beginning from His eternal existence rather than created history.",
    sourceId: "source-new-advent-john",
    rank: 100,
    tags: ["divinity", "eternity"],
  },
  {
    id: "commentary-cyril-john-1-1",
    relation: "verse",
    targetVerseId: createVerseId("kjva", "john", 1, 1),
    topicSlugs: ["logos"],
    personId: "cyril-of-alexandria",
    workId: "commentary-on-john",
    title: "The Word is not adjacent to God but fully divine",
    excerpt:
      "To say that the Word was with God and was God is to confess distinction of person without dividing the one divine glory.",
    takeaway:
      "John 1:1 is read Christologically: communion with the Father does not diminish the Son's full divinity.",
    sourceId: "source-new-advent-john",
    rank: 96,
    tags: ["christology", "trinity"],
  },
  {
    id: "commentary-basil-genesis-1",
    relation: "chapter",
    targetChapterId: createChapterId("genesis", 1),
    topicSlugs: ["creation", "light"],
    personId: "basil-the-great",
    workId: "hexaemeron",
    title: "Creation begins by God's free act",
    excerpt:
      "The scriptural beginning marks the entrance of creation, not a limit placed on the divine life before the world.",
    takeaway:
      "Genesis 1 teaches creation's dependence on God while refusing to treat God as a being inside created time.",
    sourceId: "source-ccel-hexaemeron",
    rank: 92,
    tags: ["creation", "time"],
  },
  {
    id: "commentary-theophylact-john-1-14",
    relation: "verse",
    targetVerseId: createVerseId("kjva", "john", 1, 14),
    topicSlugs: ["incarnation"],
    personId: "theophylact-of-ohrid",
    workId: "explanation-of-john",
    title: "The Word truly entered our condition",
    excerpt:
      "The Word did not merely appear among us, but truly took flesh, so that what is ours might be illumined and healed from within.",
    takeaway:
      "John 1:14 grounds salvation in the reality of the Incarnation, not in a symbolic appearance.",
    sourceId: "source-public-pdf-anthology",
    rank: 94,
    tags: ["incarnation", "salvation"],
  },
  {
    id: "commentary-chrysostom-john-1-4",
    relation: "verse",
    targetVerseId: createVerseId("kjva", "john", 1, 4),
    topicSlugs: ["light"],
    personId: "john-chrysostom",
    workId: "homilies-on-john",
    title: "Life and light are inseparable in Christ",
    excerpt:
      "John names the life that is in the Word so that the hearer might understand light not as a created brightness alone, but as the source of spiritual illumination.",
    takeaway:
      "The life of Christ is presented as light because communion with Him gives true understanding and restoration.",
    sourceId: "source-new-advent-john",
    rank: 90,
    tags: ["illumination", "life"],
  },
  {
    id: "related-athanasius-second-peter-1-4",
    relation: "related-topic",
    targetVerseId: createVerseId("kjva", "second-peter", 1, 4),
    topicSlugs: ["theosis", "incarnation"],
    personId: "athanasius-the-great",
    workId: "on-the-incarnation",
    title: "The Word's descent and our renewal",
    excerpt:
      "Humanity is restored by the Word's union with our nature, so that life in Christ becomes more than moral improvement: it is a real renewal in communion with God.",
    takeaway:
      "This is not direct verse commentary, but it is foundational for reading participation in divine life through the Incarnation.",
    sourceId: "source-public-pdf-anthology",
    rank: 74,
    tags: ["theosis", "healing"],
  },
  {
    id: "related-palamas-second-peter-1-4",
    relation: "related-topic",
    targetVerseId: createVerseId("kjva", "second-peter", 1, 4),
    topicSlugs: ["theosis", "light"],
    personId: "gregory-palamas",
    workId: "triads",
    title: "Participation is by grace, not by essence",
    excerpt:
      "To become a partaker of divine nature is to receive the life of God truly by grace, while the divine essence remains transcendent and unconfused.",
    takeaway:
      "Palamas helps the reader distinguish authentic Orthodox theosis from any collapse between Creator and creature.",
    sourceId: "source-public-pdf-anthology",
    rank: 78,
    tags: ["theosis", "energies"],
  },
];
