import type {
  CommentaryEntry,
  Person,
  SourceRecord,
  TopicTag,
  Work,
  WorkSection,
} from "@/domain/content/types";
import { createChapterId, createReference, createVerseId } from "@/lib/content/reference";

export const sourceRecords: SourceRecord[] = [
  {
    id: "source-oca-daily",
    label: "Orthodox daily calendar sample",
    collection: "Orthodox source",
    sourceType: "orthodox-web",
    url: "https://www.oca.org/saints/lives",
    note: "Used as a prototype reference for daily commemoration structure.",
    isSeeded: true,
  },
  {
    id: "source-new-advent-john",
    label: "Homilies on the Gospel of John",
    collection: "New Advent",
    sourceType: "web-collection",
    url: "https://www.newadvent.org/fathers/",
    note: "Prototype source for verse-linked patristic commentary.",
    isSeeded: true,
  },
  {
    id: "source-ccel-hexaemeron",
    label: "Hexaemeron",
    collection: "CCEL",
    sourceType: "web-collection",
    url: "https://ccel.org/",
    note: "Prototype source for creation commentary and linked excerpts.",
    isSeeded: true,
  },
  {
    id: "source-public-pdf-anthology",
    label: "Public patristic PDF anthology",
    collection: "PDF archive",
    sourceType: "pdf",
    url: "https://archive.org/",
    note: "Represents future parsed PDF-based reading material.",
    isSeeded: true,
  },
];

export const topicTags: TopicTag[] = [
  {
    slug: "logos",
    label: "Logos",
    summary: "Christ as the eternal Word through whom creation and revelation are given.",
  },
  {
    slug: "incarnation",
    label: "Incarnation",
    summary: "The Word's taking flesh for the salvation and restoration of humanity.",
  },
  {
    slug: "theosis",
    label: "Theosis",
    summary: "Participation in divine life through union with Christ by grace.",
  },
  {
    slug: "light",
    label: "Divine Light",
    summary: "The scriptural and patristic language of illumination, revelation, and life.",
  },
  {
    slug: "creation",
    label: "Creation",
    summary: "The beginning of the world and its relation to the Word and divine wisdom.",
  },
  {
    slug: "martyrdom",
    label: "Martyrdom",
    summary: "Witness sealed in blood — the laying down of life rather than the laying aside of Christ.",
  },
  {
    slug: "monasticism",
    label: "Monasticism",
    summary: "The desert tradition of solitude, ascetic struggle, and unceasing prayer.",
  },
  {
    slug: "apostleship",
    label: "Apostleship",
    summary: "Being sent: the first witnesses, their successors, and the unbroken handing-on of the faith.",
  },
  {
    slug: "hierarchy",
    label: "Hierarchy",
    summary: "The sacred order of bishops, priests, and deacons through which the mysteries are dispensed.",
  },
  {
    slug: "perseverance",
    label: "Perseverance",
    summary: "Endurance under trial — the long obedience that completes the race.",
  },
];

export const people: Person[] = [
  {
    id: "john-chrysostom",
    slug: "john-chrysostom",
    name: "John Chrysostom",
    honorific: "St.",
    kind: "father",
    eraLabel: "4th century",
    summary: "Archbishop of Constantinople whose homilies combine doctrinal clarity with pastoral directness.",
    traditions: ["Antioch", "Constantinople"],
    topicSlugs: ["logos", "incarnation", "light"],
    featuredWorkIds: ["homilies-on-john"],
    feastDayLabel: "November 13",
  },
  {
    id: "cyril-of-alexandria",
    slug: "cyril-of-alexandria",
    name: "Cyril of Alexandria",
    honorific: "St.",
    kind: "father",
    eraLabel: "5th century",
    summary: "A major Christological voice whose commentary keeps the person of Christ at the center of exegesis.",
    traditions: ["Alexandria"],
    topicSlugs: ["logos", "incarnation"],
    featuredWorkIds: ["commentary-on-john"],
    feastDayLabel: "June 9",
  },
  {
    id: "basil-the-great",
    slug: "basil-the-great",
    name: "Basil the Great",
    honorific: "St.",
    kind: "father",
    eraLabel: "4th century",
    summary: "Bishop, ascetic, and preacher whose creation homilies remain a model of theological exposition.",
    traditions: ["Cappadocia"],
    topicSlugs: ["creation", "light"],
    featuredWorkIds: ["hexaemeron"],
    feastDayLabel: "January 1",
  },
  {
    id: "athanasius-the-great",
    slug: "athanasius-the-great",
    name: "Athanasius the Great",
    honorific: "St.",
    kind: "father",
    eraLabel: "4th century",
    summary: "Defender of Nicene faith whose soteriology anchors later Orthodox teaching on deification.",
    traditions: ["Alexandria"],
    topicSlugs: ["incarnation", "theosis"],
    featuredWorkIds: ["on-the-incarnation"],
    feastDayLabel: "January 18",
  },
  {
    id: "gregory-palamas",
    slug: "gregory-palamas",
    name: "Gregory Palamas",
    honorific: "St.",
    kind: "saint",
    eraLabel: "14th century",
    summary: "Archbishop of Thessalonica whose defense of uncreated grace shaped Orthodox teaching on participation in divine life.",
    traditions: ["Byzantine"],
    topicSlugs: ["theosis", "light"],
    featuredWorkIds: ["triads"],
    feastDayLabel: "Second Sunday of Great Lent",
  },
  {
    id: "theophylact-of-ohrid",
    slug: "theophylact-of-ohrid",
    name: "Theophylact of Ohrid",
    honorific: "Blessed",
    kind: "theologian",
    eraLabel: "11th century",
    summary: "A lucid commentator whose Gospel exegesis distills earlier Fathers into accessible interpretation.",
    traditions: ["Byzantine"],
    topicSlugs: ["logos", "incarnation"],
    featuredWorkIds: ["explanation-of-john"],
  },
  {
    id: "forty-martyrs-of-sebaste",
    slug: "forty-martyrs-of-sebaste",
    name: "The Forty Martyrs of Sebaste",
    honorific: "Holy",
    kind: "saint",
    eraLabel: "4th century",
    summary: "Roman soldiers martyred together after refusing to renounce Christ, remembered for steadfast confession and mutual courage.",
    traditions: ["Cappadocia"],
    topicSlugs: ["martyrdom", "perseverance"],
    featuredWorkIds: ["life-of-the-forty-martyrs"],
    feastDayLabel: "March 9",
  },
  {
    id: "apostle-peter",
    slug: "apostle-peter",
    name: "Peter, Chief of the Apostles",
    honorific: "St.",
    kind: "saint",
    eraLabel: "1st century",
    summary: "Brother of Andrew, a fisherman of the Sea of Galilee, called by the Lord with the words 'Follow Me.' Confessor of Christ at Caesarea Philippi, denier and weeper at the courtyard fire, restored by the lake on the morning of the Resurrection. He preached at Pentecost, founded the Church at Antioch, and was crucified head-downward at Rome under Nero around the year 67.",
    traditions: ["Galilee", "Antioch", "Rome"],
    topicSlugs: ["apostleship", "martyrdom"],
    featuredWorkIds: [],
    feastDayLabel: "June 29",
  },
  {
    id: "apostle-paul",
    slug: "apostle-paul",
    name: "Paul, Apostle to the Nations",
    honorific: "St.",
    kind: "saint",
    eraLabel: "1st century",
    summary: "A Pharisee of Tarsus, persecutor of the Church, struck down on the Damascus road by a voice from heaven and a light beyond seeing. Apostle to the Gentiles through three long missions, founder of the churches of Asia Minor, Macedonia, and Greece, and author of the letters that became the second body of the New Testament. Beheaded at Rome under Nero around 67.",
    traditions: ["Tarsus", "Antioch", "Rome"],
    topicSlugs: ["apostleship", "martyrdom", "incarnation"],
    featuredWorkIds: [],
    feastDayLabel: "June 29",
  },
  {
    id: "apostle-andrew",
    slug: "apostle-andrew",
    name: "Andrew the First-Called",
    honorific: "St.",
    kind: "saint",
    eraLabel: "1st century",
    summary: "Brother of Peter and the first of the Twelve, called by the Lord at the Jordan after the witness of John the Baptist. He preached along the Black Sea coast — Pontus, Cappadocia, Bithynia, the Scythians — founding the church at Byzantium and reaching as far as the territory of the Slavs in tradition. He was crucified on a slanted cross at Patras in Achaea.",
    traditions: ["Galilee", "Byzantine"],
    topicSlugs: ["apostleship", "martyrdom"],
    featuredWorkIds: [],
    feastDayLabel: "November 30",
  },
  {
    id: "apostle-john-the-theologian",
    slug: "apostle-john-the-theologian",
    name: "John the Theologian and Evangelist",
    honorific: "St.",
    kind: "saint",
    eraLabel: "1st century",
    summary: "The disciple whom Jesus loved, brother of James, who alone of the Twelve stood at the foot of the Cross and received the Mother of God into his keeping. He wrote the fourth Gospel at Ephesus in his old age, three short letters, and the Revelation given to him on Patmos. He alone of the Twelve was not slain by men, but laid himself in his grave at Ephesus and was taken.",
    traditions: ["Galilee", "Ephesus"],
    topicSlugs: ["apostleship", "logos", "light"],
    featuredWorkIds: [],
    feastDayLabel: "May 8 and September 26",
  },
  {
    id: "apostle-mark",
    slug: "apostle-mark",
    name: "Mark the Evangelist",
    honorific: "St.",
    kind: "saint",
    eraLabel: "1st century",
    summary: "Companion of Peter at Rome, where he wrote his Gospel from the apostle's preaching, the shortest and earliest of the four. He was sent as the first bishop of Alexandria, where he established the Church of Egypt and was dragged through the streets of the city by a rope until he gave up his soul.",
    traditions: ["Rome", "Alexandria"],
    topicSlugs: ["apostleship", "martyrdom"],
    featuredWorkIds: [],
    feastDayLabel: "April 25",
  },
  {
    id: "apostle-luke",
    slug: "apostle-luke",
    name: "Luke the Evangelist",
    honorific: "St.",
    kind: "saint",
    eraLabel: "1st century",
    summary: "A physician of Antioch and companion of Paul on his journeys, author of the third Gospel and the Acts of the Apostles. Tradition names him the first iconographer, who painted from life the first icons of the Theotokos. He reposed bishop of Thebes in Boeotia at the age of eighty-four.",
    traditions: ["Antioch", "Greece"],
    topicSlugs: ["apostleship", "incarnation"],
    featuredWorkIds: [],
    feastDayLabel: "October 18",
  },
  {
    id: "apostle-matthew",
    slug: "apostle-matthew",
    name: "Matthew the Evangelist",
    honorific: "St.",
    kind: "saint",
    eraLabel: "1st century",
    summary: "The publican Levi called from his receipt of custom by the Lord's word 'Follow Me,' who left his counting-table at once and gave a feast for his old companions of the trade. He wrote his Gospel first of all the four in Hebrew, then labored in Ethiopia, where he was given the crown of martyrdom in his old age.",
    traditions: ["Galilee", "Ethiopia"],
    topicSlugs: ["apostleship", "martyrdom"],
    featuredWorkIds: [],
    feastDayLabel: "November 16",
  },
  {
    id: "apostle-thomas",
    slug: "apostle-thomas",
    name: "Thomas the Apostle",
    honorific: "St.",
    kind: "saint",
    eraLabel: "1st century",
    summary: "Called the Twin, who would not believe without seeing, and seeing cried 'My Lord and my God' — the confession that holds together the eighth-day liturgy of Pascha. Tradition sends him preaching as far as India, where he founded the Church and was pierced through with a spear.",
    traditions: ["Galilee", "India"],
    topicSlugs: ["apostleship", "martyrdom"],
    featuredWorkIds: [],
    feastDayLabel: "October 6",
  },
  {
    id: "mary-magdalene",
    slug: "mary-magdalene",
    name: "Mary Magdalene, Equal-to-the-Apostles",
    honorific: "St.",
    kind: "saint",
    eraLabel: "1st century",
    summary: "She from whom the Lord cast out seven demons, who followed Him from Galilee to the Cross and stood with His mother at the foot of the wood. She came first to the empty tomb in the dim morning and was the first to whom the risen Christ appeared, sent by Him with the word: 'Go to my brethren.' Tradition takes her to Ephesus with the apostle John in her old age.",
    traditions: ["Galilee", "Ephesus"],
    topicSlugs: ["apostleship"],
    featuredWorkIds: [],
    feastDayLabel: "July 22",
  },
  {
    id: "john-the-forerunner",
    slug: "john-the-forerunner",
    name: "John the Forerunner and Baptist",
    honorific: "St.",
    kind: "saint",
    eraLabel: "1st century",
    summary: "Son of the priest Zacharias and Elizabeth, kinsman of the Lord, of whom the Lord said that no one born of woman is greater. He went out to the wilderness as a boy and preached the baptism of repentance at the Jordan, baptized the Lord at His coming, and was beheaded by Herod for rebuking the king's unlawful marriage. The Friend of the Bridegroom, the seal of the prophets, the voice crying in the wilderness.",
    traditions: ["Judea"],
    topicSlugs: ["martyrdom", "perseverance"],
    featuredWorkIds: [],
    feastDayLabel: "January 7, June 24, August 29, September 23",
  },
  {
    id: "nicholas-of-myra",
    slug: "nicholas-of-myra",
    name: "Nicholas the Wonderworker",
    honorific: "St.",
    kind: "saint",
    eraLabel: "4th century",
    summary: "Archbishop of Myra in Lycia whose secret almsgiving saved three sisters from sale and whose presence at the Council of Nicaea was marked by zeal against Arius. After his repose his relics streamed myrrh at Myra and continued to do so when translated to Bari in 1087. The patron of children, sailors, and the poor — beloved across the whole Orthodox world.",
    traditions: ["Lycia", "Bari"],
    topicSlugs: ["hierarchy", "perseverance"],
    featuredWorkIds: [],
    feastDayLabel: "December 6 and May 9",
  },
  {
    id: "anthony-the-great",
    slug: "anthony-the-great",
    name: "Anthony the Great",
    honorific: "St.",
    kind: "saint",
    eraLabel: "3rd–4th century",
    summary: "The Egyptian who heard the Gospel words 'sell what you have and give to the poor' as said to him personally, and went out to the desert where he became the father of all monastic life. His life, written by Athanasius, shaped Christian asceticism for all time. He lived to be one hundred and five years old, contending with demons and counseling those who came up the mountain to him.",
    traditions: ["Egyptian Desert"],
    topicSlugs: ["monasticism", "perseverance"],
    featuredWorkIds: [],
    feastDayLabel: "January 17",
  },
  {
    id: "mary-of-egypt",
    slug: "mary-of-egypt",
    name: "Mary of Egypt",
    honorific: "St.",
    kind: "saint",
    eraLabel: "5th century",
    summary: "An Alexandrian dancer and prostitute who, halted by an invisible hand at the doors of the Holy Sepulchre in Jerusalem, was given the Mother of God for her teacher and went out across the Jordan into the wilderness, where she lived forty-seven years in penitence. Found by the priest Zosimas in her old age, she received communion from him and was buried by a lion at her cell.",
    traditions: ["Alexandria", "Palestine"],
    topicSlugs: ["monasticism", "perseverance"],
    featuredWorkIds: [],
    feastDayLabel: "April 1 and the Fifth Sunday of Great Lent",
  },
  {
    id: "george-the-trophy-bearer",
    slug: "george-the-trophy-bearer",
    name: "George the Great-martyr",
    honorific: "St.",
    kind: "saint",
    eraLabel: "4th century",
    summary: "A young Cappadocian officer of the Roman army under Diocletian whose endurance through every kind of torture and his final beheading made him the icon of the soldier-saint of the East. His cult spread from Lydda through every land of Christian witness; he is patron of warriors, of England, of Georgia, and of every Christian facing the dragon.",
    traditions: ["Cappadocia", "Lydda"],
    topicSlugs: ["martyrdom", "perseverance"],
    featuredWorkIds: [],
    feastDayLabel: "April 23",
  },
  {
    id: "demetrius-of-thessalonica",
    slug: "demetrius-of-thessalonica",
    name: "Demetrius the Myrrh-streamer",
    honorific: "St.",
    kind: "saint",
    eraLabel: "4th century",
    summary: "A young proconsul of Thessalonica under Galerius who openly catechized the people of his city and was speared in the bathhouse where he had been imprisoned. His tomb has streamed fragrant myrrh ever since, and he is the principal patron of the great city of Thessalonica.",
    traditions: ["Thessalonica"],
    topicSlugs: ["martyrdom"],
    featuredWorkIds: [],
    feastDayLabel: "October 26",
  },
  {
    id: "gregory-the-theologian",
    slug: "gregory-the-theologian",
    name: "Gregory the Theologian",
    honorific: "St.",
    kind: "father",
    eraLabel: "4th century",
    summary: "Friend of Basil the Great in Cappadocia, archbishop of Constantinople, whose Five Theological Orations delivered in the small church of the Anastasia decided the dogma of the Trinity for the Second Ecumenical Council. The only one of the Fathers given the title 'the Theologian' along with the apostle John.",
    traditions: ["Cappadocia", "Constantinople"],
    topicSlugs: ["logos", "incarnation", "hierarchy"],
    featuredWorkIds: [],
    feastDayLabel: "January 25",
  },
  {
    id: "maximus-the-confessor",
    slug: "maximus-the-confessor",
    name: "Maximus the Confessor",
    honorific: "St.",
    kind: "father",
    eraLabel: "7th century",
    summary: "Monk of Chrysopolis and the great theologian of the cosmic Christ, whose long defense of the two wills of Christ against the monothelites cost him his tongue, his right hand, and finally his life in exile in Lazica. His Ambigua and Ad Thalassium are the heart of mature Byzantine theology.",
    traditions: ["Constantinople", "Africa"],
    topicSlugs: ["incarnation", "theosis", "perseverance"],
    featuredWorkIds: [],
    feastDayLabel: "January 21",
  },
  {
    id: "spyridon-of-trimythous",
    slug: "spyridon-of-trimythous",
    name: "Spyridon the Wonderworker",
    honorific: "St.",
    kind: "saint",
    eraLabel: "4th century",
    summary: "A shepherd-bishop of Trimythous on Cyprus whose simple faith at the Council of Nicaea is said to have confounded a philosopher by the parable of the brick — fire, water, and clay from one tile, as the Trinity from the one God. His incorrupt relics rest on Corfu.",
    traditions: ["Cyprus", "Corfu"],
    topicSlugs: ["hierarchy", "perseverance"],
    featuredWorkIds: [],
    feastDayLabel: "December 12",
  },
  {
    id: "john-climacus",
    slug: "john-climacus",
    name: "John of the Ladder (Climacus)",
    honorific: "St.",
    kind: "father",
    eraLabel: "7th century",
    summary: "Abbot of the monastery of Sinai, author of The Ladder of Divine Ascent, whose thirty steps map the soul's rise from renunciation to love. The work is read in every Orthodox monastery during the weeks of Great Lent, and its author commemorated on the Fourth Sunday of that fast.",
    traditions: ["Sinai"],
    topicSlugs: ["monasticism", "theosis"],
    featuredWorkIds: [],
    feastDayLabel: "March 30 and the Fourth Sunday of Great Lent",
  },
  {
    id: "pachomius-the-great",
    slug: "pachomius-the-great",
    name: "Pachomius the Great",
    honorific: "St.",
    kind: "saint",
    eraLabel: "4th century",
    summary: "The Egyptian who received from an angel the rule of cenobitic life, gathering the monks of Tabennisi into the first true monastery on the upper Nile. Where Anthony showed the desert as the school of one anchorite, Pachomius made it the school of the common life under a common rule.",
    traditions: ["Egyptian Desert"],
    topicSlugs: ["monasticism"],
    featuredWorkIds: [],
    feastDayLabel: "May 15",
  },
  {
    id: "sabbas-the-sanctified",
    slug: "sabbas-the-sanctified",
    name: "Sabbas the Sanctified",
    honorific: "St.",
    kind: "saint",
    eraLabel: "6th century",
    summary: "Father of Palestinian monasticism, founder of the Great Lavra in the Wadi Kidron between Jerusalem and the Dead Sea. The Typikon that still shapes the daily services of the Orthodox Church grew out of his community, and his lavra has been continuously inhabited by monks since his repose.",
    traditions: ["Palestine"],
    topicSlugs: ["monasticism", "hierarchy"],
    featuredWorkIds: [],
    feastDayLabel: "December 5",
  },
  {
    id: "constantine-the-great",
    slug: "constantine-the-great",
    name: "Constantine the Great, Equal-to-the-Apostles",
    honorific: "St.",
    kind: "saint",
    eraLabel: "4th century",
    summary: "The emperor who saw the sign of the Cross of light in the sky before the Milvian Bridge and conquered under that sign in 312, granted peace to the Church by the Edict of Milan, summoned the First Ecumenical Council at Nicaea in 325, and founded the new Rome on the Bosphorus. Commemorated together with his mother Helena.",
    traditions: ["Constantinople"],
    topicSlugs: ["apostleship", "hierarchy"],
    featuredWorkIds: [],
    feastDayLabel: "May 21",
  },
  {
    id: "helen-equal-to-apostles",
    slug: "helen-equal-to-apostles",
    name: "Helen, Equal-to-the-Apostles",
    honorific: "St.",
    kind: "saint",
    eraLabel: "4th century",
    summary: "Mother of the emperor Constantine, who in her old age went to the Holy Land in search of the True Cross and the holy places. Through her labor the Cross was recovered, the great Church of the Resurrection built over the empty tomb, and the basilicas of Bethlehem and Olivet established. The icon of the imperial city of God.",
    traditions: ["Constantinople", "Jerusalem"],
    topicSlugs: ["apostleship"],
    featuredWorkIds: [],
    feastDayLabel: "May 21",
  },
  {
    id: "cyril-equal-to-apostles",
    slug: "cyril-equal-to-apostles",
    name: "Cyril, Equal-to-the-Apostles",
    honorific: "St.",
    kind: "saint",
    eraLabel: "9th century",
    summary: "The younger of two brothers from Thessalonica, called 'the Philosopher' for the love of learning he brought from the imperial schools. With his brother Methodius he was sent to the Slavs of Moravia, where together they devised the alphabet that bears his name and translated the Scriptures and the liturgy into Slavonic. He reposed at Rome at the age of forty-two.",
    traditions: ["Thessalonica", "Moravia", "Rome"],
    topicSlugs: ["apostleship", "logos"],
    featuredWorkIds: [],
    feastDayLabel: "February 14 and May 11",
  },
  {
    id: "methodius-equal-to-apostles",
    slug: "methodius-equal-to-apostles",
    name: "Methodius, Equal-to-the-Apostles",
    honorific: "St.",
    kind: "saint",
    eraLabel: "9th century",
    summary: "The elder of the brothers from Thessalonica, monk and bishop, who continued the mission to the Slavs after the early repose of his brother Cyril and completed the translation of the Scriptures. The fruit of his labor is the entire Slavic Orthodox world.",
    traditions: ["Thessalonica", "Moravia"],
    topicSlugs: ["apostleship", "hierarchy"],
    featuredWorkIds: [],
    feastDayLabel: "May 11",
  },
  {
    id: "ignatius-of-antioch",
    slug: "ignatius-of-antioch",
    name: "Ignatius the God-bearer",
    honorific: "St.",
    kind: "father",
    eraLabel: "2nd century",
    summary: "Disciple of the apostle John, third bishop of Antioch after Peter, condemned to the lions in Rome under Trajan. On his way from Antioch to martyrdom he wrote seven letters to the churches that mark the earliest pattern of the Church's life — the threefold ministry, the bishop as the icon of the Father, the Eucharist as the medicine of immortality.",
    traditions: ["Antioch", "Rome"],
    topicSlugs: ["hierarchy", "martyrdom", "incarnation"],
    featuredWorkIds: [],
    feastDayLabel: "December 20 and January 29",
  },
  {
    id: "polycarp-of-smyrna",
    slug: "polycarp-of-smyrna",
    name: "Polycarp of Smyrna",
    honorific: "St.",
    kind: "father",
    eraLabel: "2nd century",
    summary: "Disciple of the apostle John, bishop of Smyrna for sixty-five years, who under Marcus Aurelius answered the proconsul's demand to revile Christ: 'Eighty and six years have I served Him, and He has done me no wrong; how then can I blaspheme my King who saved me?' Burned at the stake, then pierced through.",
    traditions: ["Smyrna"],
    topicSlugs: ["hierarchy", "martyrdom"],
    featuredWorkIds: [],
    feastDayLabel: "February 23",
  },
  {
    id: "ephraim-the-syrian",
    slug: "ephraim-the-syrian",
    name: "Ephraim the Syrian",
    honorific: "St.",
    kind: "father",
    eraLabel: "4th century",
    summary: "Deacon of Edessa whose hymns gave the Syriac-speaking world its theology in verse, and whose Lenten prayer — 'O Lord and Master of my life, take from me the spirit of sloth…' — still bows the Orthodox to the ground each weekday of Great Lent.",
    traditions: ["Syria"],
    topicSlugs: ["monasticism", "perseverance"],
    featuredWorkIds: [],
    feastDayLabel: "January 28",
  },
  {
    id: "joachim-and-anna",
    slug: "joachim-and-anna",
    name: "Joachim and Anna, the Holy God-bearing Ancestors",
    honorific: "Sts.",
    kind: "saint",
    eraLabel: "1st century BC",
    summary: "The righteous parents of the Theotokos, whose long faithfulness in barrenness God remembered. They are commemorated together on the day after the Nativity of their daughter, and Anna again on the day of her own dormition.",
    traditions: ["Nazareth"],
    topicSlugs: ["perseverance"],
    featuredWorkIds: [],
    feastDayLabel: "September 9 (joint); July 25 (Anna)",
  },
];

export const works: Work[] = [
  {
    id: "homilies-on-john",
    slug: "homilies-on-john",
    personId: "john-chrysostom",
    title: "Homilies on the Gospel of John",
    shortTitle: "Homilies on John",
    workType: "homily",
    lengthLabel: "long",
    eraLabel: "4th century",
    summary: "Chrysostom's preaching on John emphasizes the eternal Son, the Incarnation, and the moral stakes of belief.",
    topicSlugs: ["logos", "incarnation", "light"],
    sourceId: "source-new-advent-john",
    verseRefs: [createReference("john", "John", 1, 1, 18)],
  },
  {
    id: "commentary-on-john",
    slug: "commentary-on-john",
    personId: "cyril-of-alexandria",
    title: "Commentary on the Gospel of John",
    shortTitle: "Commentary on John",
    workType: "commentary",
    lengthLabel: "long",
    eraLabel: "5th century",
    summary: "Cyril reads John through the unity of Christ's person and the saving purpose of the Incarnation.",
    topicSlugs: ["logos", "incarnation"],
    sourceId: "source-new-advent-john",
    verseRefs: [createReference("john", "John", 1, 1, 18)],
  },
  {
    id: "hexaemeron",
    slug: "hexaemeron",
    personId: "basil-the-great",
    title: "Hexaemeron",
    shortTitle: "Hexaemeron",
    workType: "homily",
    lengthLabel: "medium",
    eraLabel: "4th century",
    summary: "Nine homilies on the six days of creation, attentive to theology, creation, and wonder.",
    topicSlugs: ["creation", "light"],
    sourceId: "source-ccel-hexaemeron",
    verseRefs: [createReference("genesis", "Genesis", 1, 1, 5)],
  },
  {
    id: "on-the-incarnation",
    slug: "on-the-incarnation",
    personId: "athanasius-the-great",
    title: "On the Incarnation",
    shortTitle: "On the Incarnation",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "4th century",
    summary: "Athanasius presents the saving descent of the Word and the restoration of humanity in Christ.",
    topicSlugs: ["incarnation", "theosis"],
    sourceId: "source-public-pdf-anthology",
    verseRefs: [
      createReference("john", "John", 1, 14),
      createReference("second-peter", "2 Peter", 1, 4),
    ],
  },
  {
    id: "triads",
    slug: "triads",
    personId: "gregory-palamas",
    title: "The Triads",
    shortTitle: "Triads",
    workType: "treatise",
    lengthLabel: "long",
    eraLabel: "14th century",
    summary: "Palamas articulates prayer, illumination, and participation in divine energies without confusion of essence.",
    topicSlugs: ["theosis", "light"],
    sourceId: "source-public-pdf-anthology",
    verseRefs: [
      createReference("second-peter", "2 Peter", 1, 4),
      createReference("john", "John", 1, 4),
    ],
  },
  {
    id: "explanation-of-john",
    slug: "explanation-of-john",
    personId: "theophylact-of-ohrid",
    title: "Explanation of the Holy Gospel According to John",
    shortTitle: "Explanation of John",
    workType: "commentary",
    lengthLabel: "medium",
    eraLabel: "11th century",
    summary: "A compact, readable synthesis of earlier Greek Fathers on the Johannine text.",
    topicSlugs: ["logos", "incarnation"],
    sourceId: "source-public-pdf-anthology",
    verseRefs: [createReference("john", "John", 1, 1, 18)],
  },
  {
    id: "life-of-the-forty-martyrs",
    slug: "life-of-the-forty-martyrs",
    personId: "forty-martyrs-of-sebaste",
    title: "Life of the Forty Martyrs of Sebaste",
    shortTitle: "Life of the Forty Martyrs",
    workType: "life",
    lengthLabel: "short",
    eraLabel: "4th century",
    summary: "The witness of the Forty Martyrs embodies endurance, mutual strengthening, and joy in Christ.",
    topicSlugs: ["martyrdom", "perseverance"],
    sourceId: "source-oca-daily",
    verseRefs: [],
  },
];

export const workSections: WorkSection[] = [
  {
    id: "section-athanasius-word-became-man",
    workId: "on-the-incarnation",
    label: "The Word became man for our healing",
    excerpt:
      "The Word takes what is ours so that our nature, renewed in Him, may be brought back to incorruption and communion with God.",
    sourceId: "source-public-pdf-anthology",
    verseRef: createReference("john", "John", 1, 14),
  },
  {
    id: "section-palamas-divine-light",
    workId: "triads",
    label: "Participation without confusion",
    excerpt:
      "Union with God is real and transformative, yet it is received as grace; the creature does not become the divine essence.",
    sourceId: "source-public-pdf-anthology",
    verseRef: createReference("second-peter", "2 Peter", 1, 4),
  },
  {
    id: "section-hexaemeron-beginning",
    workId: "hexaemeron",
    label: "The beginning of creation",
    excerpt:
      "The beginning does not place God inside time; it marks the first appearance of created order by His free will.",
    sourceId: "source-ccel-hexaemeron",
    verseRef: createReference("genesis", "Genesis", 1, 1),
  },
];

export const commentaryEntries: CommentaryEntry[] = [
  {
    id: "commentary-chrysostom-john-1-1",
    relation: "verse",
    targetVerseId: createVerseId("kjva", "john", 1, 1),
    topicSlugs: ["logos"],
    personId: "john-chrysostom",
    workId: "homilies-on-john",
    title: "John begins above time",
    excerpt:
      "The Evangelist does not begin with earth, genealogy, or earthly ministry, but carries the hearer immediately to the eternal being of the Only-Begotten.",
    takeaway:
      "The prologue protects Christ's divinity by beginning from His eternal existence rather than created history.",
    sourceId: "source-new-advent-john",
    rank: 100,
    tags: ["divinity", "eternity"],
  },
  {
    id: "commentary-cyril-john-1-1",
    relation: "verse",
    targetVerseId: createVerseId("kjva", "john", 1, 1),
    topicSlugs: ["logos"],
    personId: "cyril-of-alexandria",
    workId: "commentary-on-john",
    title: "The Word is not adjacent to God but fully divine",
    excerpt:
      "To say that the Word was with God and was God is to confess distinction of person without dividing the one divine glory.",
    takeaway:
      "John 1:1 is read Christologically: communion with the Father does not diminish the Son's full divinity.",
    sourceId: "source-new-advent-john",
    rank: 96,
    tags: ["christology", "trinity"],
  },
  {
    id: "commentary-basil-genesis-1",
    relation: "chapter",
    targetChapterId: createChapterId("genesis", 1),
    topicSlugs: ["creation", "light"],
    personId: "basil-the-great",
    workId: "hexaemeron",
    title: "Creation begins by God's free act",
    excerpt:
      "The scriptural beginning marks the entrance of creation, not a limit placed on the divine life before the world.",
    takeaway:
      "Genesis 1 teaches creation's dependence on God while refusing to treat God as a being inside created time.",
    sourceId: "source-ccel-hexaemeron",
    rank: 92,
    tags: ["creation", "time"],
  },
  {
    id: "commentary-theophylact-john-1-14",
    relation: "verse",
    targetVerseId: createVerseId("kjva", "john", 1, 14),
    topicSlugs: ["incarnation"],
    personId: "theophylact-of-ohrid",
    workId: "explanation-of-john",
    title: "The Word truly entered our condition",
    excerpt:
      "The Word did not merely appear among us, but truly took flesh, so that what is ours might be illumined and healed from within.",
    takeaway:
      "John 1:14 grounds salvation in the reality of the Incarnation, not in a symbolic appearance.",
    sourceId: "source-public-pdf-anthology",
    rank: 94,
    tags: ["incarnation", "salvation"],
  },
  {
    id: "commentary-chrysostom-john-1-4",
    relation: "verse",
    targetVerseId: createVerseId("kjva", "john", 1, 4),
    topicSlugs: ["light"],
    personId: "john-chrysostom",
    workId: "homilies-on-john",
    title: "Life and light are inseparable in Christ",
    excerpt:
      "John names the life that is in the Word so that the hearer might understand light not as a created brightness alone, but as the source of spiritual illumination.",
    takeaway:
      "The life of Christ is presented as light because communion with Him gives true understanding and restoration.",
    sourceId: "source-new-advent-john",
    rank: 90,
    tags: ["illumination", "life"],
  },
  {
    id: "related-athanasius-second-peter-1-4",
    relation: "related-topic",
    targetVerseId: createVerseId("kjva", "second-peter", 1, 4),
    topicSlugs: ["theosis", "incarnation"],
    personId: "athanasius-the-great",
    workId: "on-the-incarnation",
    title: "The Word's descent and our renewal",
    excerpt:
      "Humanity is restored by the Word's union with our nature, so that life in Christ becomes more than moral improvement: it is a real renewal in communion with God.",
    takeaway:
      "This is not direct verse commentary, but it is foundational for reading participation in divine life through the Incarnation.",
    sourceId: "source-public-pdf-anthology",
    rank: 74,
    tags: ["theosis", "healing"],
  },
  {
    id: "related-palamas-second-peter-1-4",
    relation: "related-topic",
    targetVerseId: createVerseId("kjva", "second-peter", 1, 4),
    topicSlugs: ["theosis", "light"],
    personId: "gregory-palamas",
    workId: "triads",
    title: "Participation is by grace, not by essence",
    excerpt:
      "To become a partaker of divine nature is to receive the life of God truly by grace, while the divine essence remains transcendent and unconfused.",
    takeaway:
      "Palamas helps the reader distinguish authentic Orthodox theosis from any collapse between Creator and creature.",
    sourceId: "source-public-pdf-anthology",
    rank: 78,
    tags: ["theosis", "energies"],
  },
];
