import type {
  BibleBook,
  BibleChapter,
  BibleTranslation,
  BibleVerse,
  CrossReference,
} from "@/domain/content/types";
import { createReference, createVerseId } from "@/lib/content/reference";

function buildChapterId(translationId: string, bookSlug: string, chapterNumber: number) {
  return `${translationId}:${bookSlug}.${chapterNumber}`;
}

function verse(
  translationId: string,
  bookSlug: string,
  chapterNumber: number,
  verseNumber: number,
  bookName: string,
  text: string,
  paragraphStart = false,
  emphasisLabel?: string,
): BibleVerse {
  return {
    id: createVerseId(translationId, bookSlug, chapterNumber, verseNumber),
    translationId,
    bookSlug,
    chapterNumber,
    verseNumber,
    referenceLabel: `${bookName} ${chapterNumber}:${verseNumber}`,
    text,
    paragraphStart,
    emphasisLabel,
  };
}

export const bibleTranslations: BibleTranslation[] = [
  {
    id: "osb",
    slug: "osb",
    abbreviation: "OSB",
    name: "Orthodox Study Bible",
    languageCode: "en",
    scriptLabel: "Latin",
    kind: "translation",
    direction: "ltr",
    traditionLabel: "Orthodox study edition",
    description: "Primary reading surface for the seeded prototype.",
    isPrimary: true,
  },
  {
    id: "rsv",
    slug: "rsv",
    abbreviation: "RSV",
    name: "Revised Standard Version",
    languageCode: "en",
    scriptLabel: "Latin",
    kind: "translation",
    direction: "ltr",
    traditionLabel: "Formal English translation",
    description: "Secondary comparison translation used in the prototype.",
  },
  {
    id: "sblgnt",
    slug: "sblgnt",
    abbreviation: "GNT",
    name: "Greek New Testament",
    languageCode: "grc",
    scriptLabel: "Greek",
    kind: "original",
    direction: "ltr",
    traditionLabel: "Original language witness",
    description: "Seeded Koine Greek excerpts for comparison.",
  },
  {
    id: "lxx",
    slug: "lxx",
    abbreviation: "LXX",
    name: "Septuagint",
    languageCode: "grc",
    scriptLabel: "Greek",
    kind: "original",
    direction: "ltr",
    traditionLabel: "Greek Old Testament",
    description: "Seeded Septuagint excerpts for Orthodox Old Testament study.",
  },
  {
    id: "wlc",
    slug: "wlc",
    abbreviation: "HB",
    name: "Hebrew Bible",
    languageCode: "he",
    scriptLabel: "Hebrew",
    kind: "original",
    direction: "rtl",
    traditionLabel: "Hebrew witness",
    description: "Seeded Hebrew excerpts for Old Testament comparison.",
  },
];

export const bibleBooks: BibleBook[] = [
  {
    id: "genesis",
    slug: "genesis",
    name: "Genesis",
    shortName: "Gen",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 50,
    order: 1,
  },
  {
    id: "wisdom",
    slug: "wisdom",
    name: "Wisdom of Solomon",
    shortName: "Wis",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 19,
    order: 25,
  },
  {
    id: "john",
    slug: "john",
    name: "John",
    shortName: "Jn",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 21,
    order: 62,
  },
  {
    id: "second-peter",
    slug: "second-peter",
    name: "2 Peter",
    shortName: "2 Pet",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 3,
    order: 75,
  },
];

export const bibleChapters: BibleChapter[] = [
  {
    id: buildChapterId("osb", "john", 1),
    translationId: "osb",
    bookSlug: "john",
    chapterNumber: 1,
    referenceLabel: "John 1",
    summary: "The eternal Word, the witness of John, and the beginning of the Gospel's high Christology.",
  },
  {
    id: buildChapterId("rsv", "john", 1),
    translationId: "rsv",
    bookSlug: "john",
    chapterNumber: 1,
    referenceLabel: "John 1",
    summary: "Comparison witness for the Prologue and its theological vocabulary.",
  },
  {
    id: buildChapterId("sblgnt", "john", 1),
    translationId: "sblgnt",
    bookSlug: "john",
    chapterNumber: 1,
    referenceLabel: "John 1",
    summary: "Greek witness for selected verses in the Johannine prologue.",
  },
  {
    id: buildChapterId("osb", "genesis", 1),
    translationId: "osb",
    bookSlug: "genesis",
    chapterNumber: 1,
    referenceLabel: "Genesis 1",
    summary: "Creation begins in God's free act, a key cross-reference for John 1.",
  },
  {
    id: buildChapterId("lxx", "genesis", 1),
    translationId: "lxx",
    bookSlug: "genesis",
    chapterNumber: 1,
    referenceLabel: "Genesis 1",
    summary: "Septuagint witness for the opening creation text.",
  },
  {
    id: buildChapterId("wlc", "genesis", 1),
    translationId: "wlc",
    bookSlug: "genesis",
    chapterNumber: 1,
    referenceLabel: "Genesis 1",
    summary: "Hebrew witness for the opening creation text.",
  },
  {
    id: buildChapterId("osb", "second-peter", 1),
    translationId: "osb",
    bookSlug: "second-peter",
    chapterNumber: 1,
    referenceLabel: "2 Peter 1",
    summary: "A core text for divine participation and theosis vocabulary.",
  },
  {
    id: buildChapterId("rsv", "second-peter", 1),
    translationId: "rsv",
    bookSlug: "second-peter",
    chapterNumber: 1,
    referenceLabel: "2 Peter 1",
    summary: "Comparison witness for theosis-related phrasing.",
  },
  {
    id: buildChapterId("osb", "wisdom", 7),
    translationId: "osb",
    bookSlug: "wisdom",
    chapterNumber: 7,
    referenceLabel: "Wisdom 7",
    summary: "Wisdom imagery that enriches Logos theology in the prototype corpus.",
  },
];

export const bibleVerses: BibleVerse[] = [
  verse("osb", "john", 1, 1, "John", "In the beginning was the Word, and the Word was with God, and the Word was God.", true, "logos"),
  verse("osb", "john", 1, 2, "John", "He was in the beginning with God."),
  verse("osb", "john", 1, 3, "John", "All things were made through Him, and without Him nothing was made that was made."),
  verse("osb", "john", 1, 4, "John", "In Him was life, and the life was the light of men.", false, "light"),
  verse("osb", "john", 1, 5, "John", "And the light shines in the darkness, and the darkness did not comprehend it."),
  verse("osb", "john", 1, 6, "John", "There was a man sent from God, whose name was John.", true),
  verse("osb", "john", 1, 7, "John", "This man came for a witness, to bear witness of the Light, that all through him might believe."),
  verse("osb", "john", 1, 8, "John", "He was not that Light, but was sent to bear witness of that Light."),
  verse("osb", "john", 1, 9, "John", "That was the true Light which gives light to every man coming into the world."),
  verse("osb", "john", 1, 10, "John", "He was in the world, and the world was made through Him, and the world did not know Him."),
  verse("osb", "john", 1, 11, "John", "He came to His own, and His own did not receive Him."),
  verse("osb", "john", 1, 12, "John", "But as many as received Him, to them He gave the right to become children of God, to those who believe in His name:"),
  verse("osb", "john", 1, 13, "John", "who were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God."),
  verse("osb", "john", 1, 14, "John", "And the Word became flesh and dwelt among us, and we beheld His glory, the glory as of the only-begotten of the Father, full of grace and truth.", true, "incarnation"),
  verse("osb", "john", 1, 15, "John", "John bore witness of Him and cried out, saying, “This was He of whom I said, ‘He who comes after me is preferred before me, for He was before me.’”"),
  verse("osb", "john", 1, 16, "John", "And of His fullness we have all received, and grace for grace."),
  verse("osb", "john", 1, 17, "John", "For the law was given through Moses, but grace and truth came through Jesus Christ."),
  verse("osb", "john", 1, 18, "John", "No one has seen God at any time. The only-begotten Son, who is in the bosom of the Father, He has declared Him."),

  verse("rsv", "john", 1, 1, "John", "In the beginning was the Word, and the Word was with God, and the Word was God.", true, "logos"),
  verse("rsv", "john", 1, 2, "John", "He was in the beginning with God."),
  verse("rsv", "john", 1, 3, "John", "All things were made through him, and without him was not anything made that was made."),
  verse("rsv", "john", 1, 4, "John", "In him was life, and the life was the light of men.", false, "light"),
  verse("rsv", "john", 1, 5, "John", "The light shines in the darkness, and the darkness has not overcome it."),
  verse("rsv", "john", 1, 14, "John", "And the Word became flesh and dwelt among us, full of grace and truth; we have beheld his glory, glory as of the only Son from the Father.", true, "incarnation"),
  verse("rsv", "second-peter", 1, 4, "2 Peter", "By these he has granted to us his precious and very great promises, that through these you may escape from the corruption that is in the world because of passion, and become partakers of the divine nature.", true, "theosis"),

  verse("sblgnt", "john", 1, 1, "John", "Ἐν ἀρχῇ ἦν ὁ λόγος, καὶ ὁ λόγος ἦν πρὸς τὸν θεόν, καὶ θεὸς ἦν ὁ λόγος.", true),
  verse("sblgnt", "john", 1, 2, "John", "οὗτος ἦν ἐν ἀρχῇ πρὸς τὸν θεόν."),
  verse("sblgnt", "john", 1, 3, "John", "πάντα δι’ αὐτοῦ ἐγένετο, καὶ χωρὶς αὐτοῦ ἐγένετο οὐδὲ ἕν."),
  verse("sblgnt", "john", 1, 4, "John", "ὃ γέγονεν ἐν αὐτῷ ζωὴ ἦν, καὶ ἡ ζωὴ ἦν τὸ φῶς τῶν ἀνθρώπων·"),
  verse("sblgnt", "john", 1, 5, "John", "καὶ τὸ φῶς ἐν τῇ σκοτίᾳ φαίνει, καὶ ἡ σκοτία αὐτὸ οὐ κατέλαβεν."),
  verse("sblgnt", "john", 1, 14, "John", "Καὶ ὁ λόγος σὰρξ ἐγένετο καὶ ἐσκήνωσεν ἐν ἡμῖν, καὶ ἐθεασάμεθα τὴν δόξαν αὐτοῦ.", true),
  verse("sblgnt", "second-peter", 1, 4, "2 Peter", "δι’ ὧν τὰ τίμια καὶ μέγιστα ἡμῖν ἐπαγγέλματα δεδώρηται, ἵνα διὰ τούτων γένησθε θείας κοινωνοὶ φύσεως.", true),

  verse("osb", "genesis", 1, 1, "Genesis", "In the beginning God made heaven and earth.", true, "creation"),
  verse("osb", "genesis", 1, 2, "Genesis", "Yet the earth was unseen and unfurnished, and darkness was over the deep. And the Spirit of God was hovering over the face of the waters."),
  verse("osb", "genesis", 1, 3, "Genesis", "Then God said, “Let there be light”; and there was light."),
  verse("osb", "genesis", 1, 4, "Genesis", "God saw the light, that it was good; and God divided the light from the darkness."),
  verse("osb", "genesis", 1, 5, "Genesis", "God called the light Day, and the darkness He called Night. So the evening and the morning were the first day."),

  verse("lxx", "genesis", 1, 1, "Genesis", "Ἐν ἀρχῇ ἐποίησεν ὁ Θεὸς τὸν οὐρανὸν καὶ τὴν γῆν.", true),
  verse("lxx", "genesis", 1, 2, "Genesis", "ἡ δὲ γῆ ἦν ἀόρατος καὶ ἀκατασκεύαστος, καὶ σκότος ἐπάνω τῆς ἀβύσσου."),
  verse("lxx", "genesis", 1, 3, "Genesis", "καὶ εἶπεν ὁ Θεός· γενηθήτω φῶς. καὶ ἐγένετο φῶς."),

  verse("wlc", "genesis", 1, 1, "Genesis", "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ׃", true),
  verse("wlc", "genesis", 1, 2, "Genesis", "וְהָאָרֶץ הָיְתָה תֹהוּ וָבֹהוּ וְחֹשֶׁךְ עַל פְּנֵי תְהוֹם׃"),
  verse("wlc", "genesis", 1, 3, "Genesis", "וַיֹּאמֶר אֱלֹהִים יְהִי אוֹר וַיְהִי אוֹר׃"),

  verse("osb", "second-peter", 1, 2, "2 Peter", "Grace and peace be multiplied to you in the knowledge of God and of Jesus our Lord,", true),
  verse("osb", "second-peter", 1, 3, "2 Peter", "as His divine power has given to us all things that pertain to life and godliness, through the knowledge of Him who called us by glory and virtue,"),
  verse("osb", "second-peter", 1, 4, "2 Peter", "by which have been given to us exceedingly great and precious promises, that through these you may be partakers of the divine nature, having escaped the corruption that is in the world through lust.", false, "theosis"),
  verse("osb", "second-peter", 1, 5, "2 Peter", "But also for this very reason, giving all diligence, add to your faith virtue, to virtue knowledge,"),
  verse("osb", "second-peter", 1, 6, "2 Peter", "to knowledge self-control, to self-control perseverance, to perseverance godliness,"),
  verse("osb", "second-peter", 1, 7, "2 Peter", "to godliness brotherly kindness, and to brotherly kindness love."),
  verse("osb", "second-peter", 1, 8, "2 Peter", "For if these things are yours and abound, you will be neither barren nor unfruitful in the knowledge of our Lord Jesus Christ."),

  verse("osb", "wisdom", 7, 25, "Wisdom", "For she is a breath of the power of God, and a pure emanation of the glory of the Almighty.", true, "wisdom"),
  verse("osb", "wisdom", 7, 26, "Wisdom", "For she is the brightness of everlasting light, the unspotted mirror of the working of God, and the image of His goodness."),
  verse("osb", "wisdom", 7, 27, "Wisdom", "Although she is one, she can do all things; and while remaining in herself, she makes all things new."),
];

export const crossReferences: CrossReference[] = [
  {
    id: "xref-john-1-1-genesis-1-1",
    fromVerseId: createVerseId("osb", "john", 1, 1),
    target: createReference("genesis", "Genesis", 1, 1),
    relation: "parallel",
    note: "John's opening deliberately echoes Genesis to identify the Word with the Creator.",
  },
  {
    id: "xref-john-1-1-hebrews-1-2",
    fromVerseId: createVerseId("osb", "john", 1, 1),
    target: createReference("hebrews", "Hebrews", 1, 2, 3),
    relation: "theme",
    note: "The Son is presented as the one through whom God made the ages.",
  },
  {
    id: "xref-john-1-4-genesis-1-3",
    fromVerseId: createVerseId("osb", "john", 1, 4),
    target: createReference("genesis", "Genesis", 1, 3),
    relation: "parallel",
    note: "Light in John is theological and personal, but still resonates with the first creation light.",
  },
  {
    id: "xref-john-1-14-philippians-2-6",
    fromVerseId: createVerseId("osb", "john", 1, 14),
    target: createReference("philippians", "Philippians", 2, 6, 8),
    relation: "theme",
    note: "The Word's becoming flesh is illuminated by the apostolic hymn of self-emptying.",
  },
  {
    id: "xref-second-peter-1-4-john-17-21",
    fromVerseId: createVerseId("osb", "second-peter", 1, 4),
    target: createReference("john", "John", 17, 21, 23),
    relation: "theme",
    note: "Participation in divine life should be read as communion in Christ, not confusion of essences.",
  },
  {
    id: "xref-second-peter-1-4-wisdom-7-26",
    fromVerseId: createVerseId("osb", "second-peter", 1, 4),
    target: createReference("wisdom", "Wisdom of Solomon", 7, 26),
    relation: "theme",
    note: "Wisdom language helps frame participation as radiant communion with divine life.",
  },
];
