import type {
  BibleBook,
  BibleChapter,
  BibleTranslation,
  BibleVerse,
  CrossReference,
} from "@/domain/content/types";
import { createReference, createVerseId } from "@/lib/content/reference";

function buildChapterId(translationId: string, bookSlug: string, chapterNumber: number) {
  return `${translationId}:${bookSlug}.${chapterNumber}`;
}

function verse(
  translationId: string,
  bookSlug: string,
  chapterNumber: number,
  verseNumber: number,
  bookName: string,
  text: string,
  paragraphStart = false,
  emphasisLabel?: string,
): BibleVerse {
  return {
    id: createVerseId(translationId, bookSlug, chapterNumber, verseNumber),
    translationId,
    bookSlug,
    chapterNumber,
    verseNumber,
    referenceLabel: `${bookName} ${chapterNumber}:${verseNumber}`,
    text,
    paragraphStart,
    emphasisLabel,
  };
}

export const bibleTranslations: BibleTranslation[] = [
  {
    id: "kjva",
    slug: "kjva",
    abbreviation: "KJVA",
    name: "King James Version with Apocrypha",
    languageCode: "en",
    scriptLabel: "Latin",
    kind: "translation",
    direction: "ltr",
    traditionLabel: "English translation",
    description: "Primary reading surface for the prototype.",
    isPrimary: true,
  },
  {
    id: "rsv",
    slug: "rsv",
    abbreviation: "RSV",
    name: "Revised Standard Version",
    languageCode: "en",
    scriptLabel: "Latin",
    kind: "translation",
    direction: "ltr",
    traditionLabel: "Formal English translation",
    description: "Secondary comparison translation used in the prototype.",
  },
  {
    id: "sblgnt",
    slug: "sblgnt",
    abbreviation: "GNT",
    name: "Greek New Testament",
    languageCode: "grc",
    scriptLabel: "Greek",
    kind: "original",
    direction: "ltr",
    traditionLabel: "Original language witness",
    description: "Seeded Koine Greek excerpts for comparison.",
  },
  {
    id: "lxx",
    slug: "lxx",
    abbreviation: "LXX",
    name: "Septuagint",
    languageCode: "grc",
    scriptLabel: "Greek",
    kind: "original",
    direction: "ltr",
    traditionLabel: "Greek Old Testament",
    description: "Seeded Septuagint excerpts for Orthodox Old Testament study.",
  },
  {
    id: "wlc",
    slug: "wlc",
    abbreviation: "HB",
    name: "Hebrew Bible",
    languageCode: "he",
    scriptLabel: "Hebrew",
    kind: "original",
    direction: "rtl",
    traditionLabel: "Hebrew witness",
    description: "Seeded Hebrew excerpts for Old Testament comparison.",
  },
];

export const bibleBooks: BibleBook[] = [
  {
    id: "genesis",
    slug: "genesis",
    name: "Genesis",
    shortName: "Gen",
    canonDivision: "old-testament",
    testamentLabel: "Old Testament",
    chapterCount: 50,
    order: 1,
  },
  {
    id: "wisdom",
    slug: "wisdom",
    name: "Wisdom of Solomon",
    shortName: "Wis",
    canonDivision: "deuterocanon",
    testamentLabel: "Deuterocanon",
    chapterCount: 19,
    order: 25,
  },
  {
    id: "john",
    slug: "john",
    name: "John",
    shortName: "Jn",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 21,
    order: 62,
  },
  {
    id: "second-peter",
    slug: "second-peter",
    name: "2 Peter",
    shortName: "2 Pet",
    canonDivision: "new-testament",
    testamentLabel: "New Testament",
    chapterCount: 3,
    order: 75,
  },
];

export const bibleChapters: BibleChapter[] = [
  {
    id: buildChapterId("osb", "john", 1),
    translationId: "osb",
    bookSlug: "john",
    chapterNumber: 1,
    referenceLabel: "John 1",
    summary: "The eternal Word, the witness of John, and the beginning of the Gospel's high Christology.",
  },
  {
    id: buildChapterId("rsv", "john", 1),
    translationId: "rsv",
    bookSlug: "john",
    chapterNumber: 1,
    referenceLabel: "John 1",
    summary: "Comparison witness for the Prologue and its theological vocabulary.",
  },
  {
    id: buildChapterId("sblgnt", "john", 1),
    translationId: "sblgnt",
    bookSlug: "john",
    chapterNumber: 1,
    referenceLabel: "John 1",
    summary: "Greek witness for selected verses in the Johannine prologue.",
  },
  {
    id: buildChapterId("osb", "genesis", 1),
    translationId: "osb",
    bookSlug: "genesis",
    chapterNumber: 1,
    referenceLabel: "Genesis 1",
    summary: "Creation begins in God's free act, a key cross-reference for John 1.",
  },
  {
    id: buildChapterId("lxx", "genesis", 1),
    translationId: "lxx",
    bookSlug: "genesis",
    chapterNumber: 1,
    referenceLabel: "Genesis 1",
    summary: "Septuagint witness for the opening creation text.",
  },
  {
    id: buildChapterId("wlc", "genesis", 1),
    translationId: "wlc",
    bookSlug: "genesis",
    chapterNumber: 1,
    referenceLabel: "Genesis 1",
    summary: "Hebrew witness for the opening creation text.",
  },
  {
    id: buildChapterId("osb", "second-peter", 1),
    translationId: "osb",
    bookSlug: "second-peter",
    chapterNumber: 1,
    referenceLabel: "2 Peter 1",
    summary: "A core text for divine participation and theosis vocabulary.",
  },
  {
    id: buildChapterId("rsv", "second-peter", 1),
    translationId: "rsv",
    bookSlug: "second-peter",
    chapterNumber: 1,
    referenceLabel: "2 Peter 1",
    summary: "Comparison witness for theosis-related phrasing.",
  },
  {
    id: buildChapterId("osb", "wisdom", 7),
    translationId: "osb",
    bookSlug: "wisdom",
    chapterNumber: 7,
    referenceLabel: "Wisdom 7",
    summary: "Wisdom imagery that enriches Logos theology in the prototype corpus.",
  },
];

export const bibleVerses: BibleVerse[] = [
  verse("kjva", "john", 1, 1, "John", "In the beginning was the Word, and the Word was with God, and the Word was God.", true, "logos"),
  verse("kjva", "john", 1, 2, "John", "The same was in the beginning with God."),
  verse("kjva", "john", 1, 3, "John", "All things were made by him; and without him was not any thing made that was made."),
  verse("kjva", "john", 1, 4, "John", "In him was life; and the life was the light of men.", false, "light"),
  verse("kjva", "john", 1, 5, "John", "And the light shineth in darkness; and the darkness comprehended it not."),
  verse("kjva", "john", 1, 6, "John", "There was a man sent from God, whose name was John.", true),
  verse("kjva", "john", 1, 7, "John", "The same came for a witness, to bear witness of the Light, that all men through him might believe."),
  verse("kjva", "john", 1, 8, "John", "He was not that Light, but was sent to bear witness of that Light."),
  verse("kjva", "john", 1, 9, "John", "That was the true Light, which lighteth every man that cometh into the world."),
  verse("kjva", "john", 1, 10, "John", "He was in the world, and the world was made by him, and the world knew him not."),
  verse("kjva", "john", 1, 11, "John", "He came unto his own, and his own received him not."),
  verse("kjva", "john", 1, 12, "John", "But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name:"),
  verse("kjva", "john", 1, 13, "John", "Which were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God."),
  verse("kjva", "john", 1, 14, "John", "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth.", true, "incarnation"),
  verse("kjva", "john", 1, 15, "John", "John bare witness of him, and cried, saying, This was he of whom I spake, He that cometh after me is preferred before me: for he was before me."),
  verse("kjva", "john", 1, 16, "John", "And of his fulness have all we received, and grace for grace."),
  verse("kjva", "john", 1, 17, "John", "For the law was given by Moses, but grace and truth came by Jesus Christ."),
  verse("kjva", "john", 1, 18, "John", "No man hath seen God at any time; the only begotten Son, which is in the bosom of the Father, he hath declared him."),

  verse("rsv", "john", 1, 1, "John", "In the beginning was the Word, and the Word was with God, and the Word was God.", true, "logos"),
  verse("rsv", "john", 1, 2, "John", "He was in the beginning with God."),
  verse("rsv", "john", 1, 3, "John", "All things were made through him, and without him was not anything made that was made."),
  verse("rsv", "john", 1, 4, "John", "In him was life, and the life was the light of men.", false, "light"),
  verse("rsv", "john", 1, 5, "John", "The light shines in the darkness, and the darkness has not overcome it."),
  verse("rsv", "john", 1, 14, "John", "And the Word became flesh and dwelt among us, full of grace and truth; we have beheld his glory, glory as of the only Son from the Father.", true, "incarnation"),
  verse("rsv", "second-peter", 1, 4, "2 Peter", "By these he has granted to us his precious and very great promises, that through these you may escape from the corruption that is in the world because of passion, and become partakers of the divine nature.", true, "theosis"),

  verse("sblgnt", "john", 1, 1, "John", "Ἐν ἀρχῇ ἦν ὁ λόγος, καὶ ὁ λόγος ἦν πρὸς τὸν θεόν, καὶ θεὸς ἦν ὁ λόγος.", true),
  verse("sblgnt", "john", 1, 2, "John", "οὗτος ἦν ἐν ἀρχῇ πρὸς τὸν θεόν."),
  verse("sblgnt", "john", 1, 3, "John", "πάντα δι’ αὐτοῦ ἐγένετο, καὶ χωρὶς αὐτοῦ ἐγένετο οὐδὲ ἕν."),
  verse("sblgnt", "john", 1, 4, "John", "ὃ γέγονεν ἐν αὐτῷ ζωὴ ἦν, καὶ ἡ ζωὴ ἦν τὸ φῶς τῶν ἀνθρώπων·"),
  verse("sblgnt", "john", 1, 5, "John", "καὶ τὸ φῶς ἐν τῇ σκοτίᾳ φαίνει, καὶ ἡ σκοτία αὐτὸ οὐ κατέλαβεν."),
  verse("sblgnt", "john", 1, 14, "John", "Καὶ ὁ λόγος σὰρξ ἐγένετο καὶ ἐσκήνωσεν ἐν ἡμῖν, καὶ ἐθεασάμεθα τὴν δόξαν αὐτοῦ.", true),
  verse("sblgnt", "second-peter", 1, 4, "2 Peter", "δι’ ὧν τὰ τίμια καὶ μέγιστα ἡμῖν ἐπαγγέλματα δεδώρηται, ἵνα διὰ τούτων γένησθε θείας κοινωνοὶ φύσεως.", true),

  verse("kjva", "genesis", 1, 1, "Genesis", "In the beginning God created the heaven and the earth.", true, "creation"),
  verse("kjva", "genesis", 1, 2, "Genesis", "And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters."),
  verse("kjva", "genesis", 1, 3, "Genesis", "And God said, Let there be light: and there was light."),
  verse("kjva", "genesis", 1, 4, "Genesis", "And God saw the light, that it was good: and God divided the light from the darkness."),
  verse("kjva", "genesis", 1, 5, "Genesis", "And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day."),

  verse("lxx", "genesis", 1, 1, "Genesis", "Ἐν ἀρχῇ ἐποίησεν ὁ Θεὸς τὸν οὐρανὸν καὶ τὴν γῆν.", true),
  verse("lxx", "genesis", 1, 2, "Genesis", "ἡ δὲ γῆ ἦν ἀόρατος καὶ ἀκατασκεύαστος, καὶ σκότος ἐπάνω τῆς ἀβύσσου."),
  verse("lxx", "genesis", 1, 3, "Genesis", "καὶ εἶπεν ὁ Θεός· γενηθήτω φῶς. καὶ ἐγένετο φῶς."),

  verse("wlc", "genesis", 1, 1, "Genesis", "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ׃", true),
  verse("wlc", "genesis", 1, 2, "Genesis", "וְהָאָרֶץ הָיְתָה תֹהוּ וָבֹהוּ וְחֹשֶׁךְ עַל פְּנֵי תְהוֹם׃"),
  verse("wlc", "genesis", 1, 3, "Genesis", "וַיֹּאמֶר אֱלֹהִים יְהִי אוֹר וַיְהִי אוֹר׃"),

  verse("kjva", "second-peter", 1, 2, "2 Peter", "Grace and peace be multiplied unto you through the knowledge of God, and of Jesus our Lord,", true),
  verse("kjva", "second-peter", 1, 3, "2 Peter", "According as his divine power hath given unto us all things that pertain unto life and godliness, through the knowledge of him that hath called us to glory and virtue:"),
  verse("kjva", "second-peter", 1, 4, "2 Peter", "Whereby are given unto us exceeding great and precious promises: that by these ye might be partakers of the divine nature, having escaped the corruption that is in the world through lust.", false, "theosis"),
  verse("kjva", "second-peter", 1, 5, "2 Peter", "And beside this, giving all diligence, add to your faith virtue; and to virtue knowledge;"),
  verse("kjva", "second-peter", 1, 6, "2 Peter", "And to knowledge temperance; and to temperance patience; and to patience godliness;"),
  verse("kjva", "second-peter", 1, 7, "2 Peter", "And to godliness brotherly kindness; and to brotherly kindness charity."),
  verse("kjva", "second-peter", 1, 8, "2 Peter", "For if these things be in you, and abound, they make you that ye shall neither be barren nor unfruitful in the knowledge of our Lord Jesus Christ."),

  verse("kjva", "wisdom", 7, 25, "Wisdom", "For she is the breath of the power of God, and a pure influence flowing from the glory of the Almighty: therefore can no defiled thing fall into her.", true, "wisdom"),
  verse("kjva", "wisdom", 7, 26, "Wisdom", "For she is the brightness of the everlasting light, the unspotted mirror of the power of God, and the image of his goodness."),
  verse("kjva", "wisdom", 7, 27, "Wisdom", "And being but one, she can do all things: and remaining in herself, she maketh all things new: and in all ages entering into holy souls, she maketh them friends of God, and prophets."),
];

export const crossReferences: CrossReference[] = [
  {
    id: "xref-john-1-1-genesis-1-1",
    fromVerseId: createVerseId("kjva", "john", 1, 1),
    target: createReference("genesis", "Genesis", 1, 1),
    relation: "parallel",
    note: "John's opening deliberately echoes Genesis to identify the Word with the Creator.",
  },
  {
    id: "xref-john-1-1-hebrews-1-2",
    fromVerseId: createVerseId("kjva", "john", 1, 1),
    target: createReference("hebrews", "Hebrews", 1, 2, 3),
    relation: "theme",
    note: "The Son is presented as the one through whom God made the ages.",
  },
  {
    id: "xref-john-1-4-genesis-1-3",
    fromVerseId: createVerseId("kjva", "john", 1, 4),
    target: createReference("genesis", "Genesis", 1, 3),
    relation: "parallel",
    note: "Light in John is theological and personal, but still resonates with the first creation light.",
  },
  {
    id: "xref-john-1-14-philippians-2-6",
    fromVerseId: createVerseId("kjva", "john", 1, 14),
    target: createReference("philippians", "Philippians", 2, 6, 8),
    relation: "theme",
    note: "The Word's becoming flesh is illuminated by the apostolic hymn of self-emptying.",
  },
  {
    id: "xref-second-peter-1-4-john-17-21",
    fromVerseId: createVerseId("kjva", "second-peter", 1, 4),
    target: createReference("john", "John", 17, 21, 23),
    relation: "theme",
    note: "Participation in divine life should be read as communion in Christ, not confusion of essences.",
  },
  {
    id: "xref-second-peter-1-4-wisdom-7-26",
    fromVerseId: createVerseId("kjva", "second-peter", 1, 4),
    target: createReference("wisdom", "Wisdom of Solomon", 7, 26),
    relation: "theme",
    note: "Wisdom language helps frame participation as radiant communion with divine life.",
  },
];
