// Walk every saint and father in the seed library, search Wikimedia Commons
// for a PD/CC0 icon matching the name, and write a generated sources file
// (sources-auto.ts) that the regular fetch-wikimedia.ts ingester then picks
// up alongside the hand-curated sources.ts.
//
// Idempotent: re-running re-reads sources-auto.ts and skips saints already
// resolved. Saints that didn't match anything also get a "miss" marker so we
// don't keep searching them every run.

import fs from "node:fs";
import path from "node:path";
import { iconSources } from "./sources";

// Don't import "@/lib/content/seed/library" — that path alias is broken under
// the mobile/expo tsconfig. Parse the seed module as text and also pull people
// from the generated commentary bundles' library catalog.
type SeedPerson = { id: string; name: string; kind: string };

function loadPeople(): SeedPerson[] {
  const seen = new Set<string>();
  const out: SeedPerson[] = [];

  // 1) Seed library.ts (parse as text to dodge the broken @/ alias).
  const seedPath = path.join(process.cwd(), "src/lib/content/seed/library.ts");
  if (fs.existsSync(seedPath)) {
    const raw = fs.readFileSync(seedPath, "utf8");
    const re = /\{\s*id:\s*"([^"]+)",\s*slug:\s*"[^"]+",\s*name:\s*"([^"]+)",(?:\s*honorific:\s*"[^"]+",)?\s*kind:\s*"(saint|father|theologian)"/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(raw)) !== null) {
      if (!seen.has(m[1])) {
        seen.add(m[1]);
        out.push({ id: m[1], name: m[2], kind: m[3] });
      }
    }
  }

  // 2) Normalized library catalog (generated by the commentary normalize step).
  const libCatalogPath = path.join(
    process.cwd(),
    "content/normalized/library/catalog.json",
  );
  if (fs.existsSync(libCatalogPath)) {
    try {
      const cat = JSON.parse(fs.readFileSync(libCatalogPath, "utf8")) as {
        people?: Array<{ id: string; name: string; kind: string }>;
      };
      for (const p of cat.people ?? []) {
        if (!seen.has(p.id)) {
          seen.add(p.id);
          out.push({ id: p.id, name: p.name, kind: p.kind });
        }
      }
    } catch {
      // ignore — leave seed-only
    }
  }

  return out;
}

const people = loadPeople();

const REPO_ROOT = process.cwd();
const AUTO_SOURCES_PATH = path.join(
  REPO_ROOT,
  "scripts/ingest/icons/sources-auto.ts",
);
const MISSES_PATH = path.join(
  REPO_ROOT,
  "scripts/ingest/icons/sources-auto-misses.json",
);
const USER_AGENT = "TheosisIconIngest/0.1 (https://github.com/theosis-app)";

type AutoEntry = {
  id: string;
  personId: string;
  wikimediaTitle: string;
  alt: string;
  caption: string;
};

type SearchResult = { title: string };

type ImageInfo = {
  title: string;
  url: string;
  license: string;
};

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

// Strip honorifics and Orthodox titles for cleaner search queries.
function cleanNameForSearch(name: string): string {
  return name
    .replace(/^(St\.?|Saint|Sts\.?|Holy)\s+/i, "")
    .replace(/^(Apostle|Prophet|Martyr|Hieromartyr|Equal-to-the-Apostles|Venerable|Right-Believing|Great-martyr)\s+/i, "")
    .replace(/^the\s+/i, "")
    .trim();
}

async function searchCommons(query: string): Promise<SearchResult[]> {
  const url =
    "https://commons.wikimedia.org/w/api.php" +
    "?action=query&format=json&list=search&srnamespace=6&srlimit=10" +
    "&srsearch=" +
    encodeURIComponent(query);
  const res = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
  if (!res.ok) throw new Error(`Search ${res.status}: ${query}`);
  const data = (await res.json()) as {
    query?: { search?: SearchResult[] };
  };
  return data.query?.search ?? [];
}

async function listCategoryFiles(category: string): Promise<SearchResult[]> {
  const url =
    "https://commons.wikimedia.org/w/api.php" +
    "?action=query&format=json&list=categorymembers&cmtype=file&cmlimit=15" +
    "&cmtitle=" +
    encodeURIComponent(category);
  const res = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
  if (!res.ok) return [];
  const data = (await res.json()) as {
    query?: { categorymembers?: Array<{ title: string }> };
  };
  return (data.query?.categorymembers ?? []).map((m) => ({ title: m.title }));
}

type WikidataEntity = {
  id: string;
  label: string;
  description: string;
};

async function searchWikidata(query: string): Promise<WikidataEntity[]> {
  const url =
    "https://www.wikidata.org/w/api.php" +
    "?action=wbsearchentities&format=json&language=en&type=item&limit=8" +
    "&search=" +
    encodeURIComponent(query);
  const res = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
  if (!res.ok) return [];
  const data = (await res.json()) as {
    search?: Array<{ id: string; label?: string; description?: string }>;
  };
  return (data.search ?? []).map((s) => ({
    id: s.id,
    label: s.label ?? "",
    description: s.description ?? "",
  }));
}

// Fetch a Wikidata entity's P18 (image) claim value, which is just the bare
// Commons filename (no "File:" prefix, e.g. "Saint Anthony icon.jpg").
async function getWikidataImage(qid: string): Promise<string | null> {
  const url =
    "https://www.wikidata.org/w/api.php" +
    "?action=wbgetentities&format=json&props=claims&ids=" +
    encodeURIComponent(qid);
  const res = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
  if (!res.ok) return null;
  const data = (await res.json()) as {
    entities?: Record<
      string,
      {
        claims?: {
          P18?: Array<{
            mainsnak?: { datavalue?: { value?: string } };
          }>;
        };
      }
    >;
  };
  const entity = data.entities?.[qid];
  const filename = entity?.claims?.P18?.[0]?.mainsnak?.datavalue?.value;
  return typeof filename === "string" ? filename : null;
}

async function imageInfo(title: string): Promise<ImageInfo | null> {
  const url =
    "https://commons.wikimedia.org/w/api.php" +
    "?action=query&format=json&prop=imageinfo" +
    "&iiprop=url|extmetadata&titles=" +
    encodeURIComponent(title);
  const res = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
  if (!res.ok) return null;
  const data = (await res.json()) as {
    query?: {
      pages?: Record<
        string,
        {
          title?: string;
          imageinfo?: Array<{
            url: string;
            extmetadata?: Record<string, { value: string }>;
          }>;
        }
      >;
    };
  };
  const page = Object.values(data.query?.pages ?? {})[0];
  const info = page?.imageinfo?.[0];
  if (!info) return null;
  const license =
    info.extmetadata?.LicenseShortName?.value ??
    info.extmetadata?.License?.value ??
    "";
  return { title: page?.title ?? title, url: info.url, license };
}

function isAcceptable(license: string): boolean {
  const lower = license.toLowerCase();
  return (
    lower.includes("public domain") ||
    lower === "pd" ||
    lower.includes("cc0") ||
    lower.includes("cc by") ||
    lower.includes("cc-by")
  );
}

// Tokens to ignore when checking that the saint's name appears in a result
// title. Most are honorifics/qualifiers that show up on tons of unrelated icons.
const NAME_STOPWORDS = new Set([
  "the", "of", "and", "saint", "saints", "holy", "great", "elder", "younger",
  "new", "old", "wonderworker", "confessor", "martyr", "prophet", "apostle",
  "hieromartyr", "archbishop", "bishop", "patriarch", "monk", "father",
  "bears", "icon", "orthodox", "russian", "greek", "byzantine", "menaion",
  "moscow", "kiev", "rome", "constantinople", "alexandria", "antioch",
]);

// Negative filter: titles that are definitely NOT the icon we want
// (PDFs, calendar sheets, building surveys). Shared by both strict and
// relaxed icon detection.
function isObviouslyNotAnIcon(title: string): boolean {
  const lower = title.toLowerCase();
  if (lower.endsWith(".pdf") || lower.endsWith(".djvu")) return true;
  // Generic Menaion calendar sheets list dozens of saints.
  if (/menaion icon\s*\(/i.test(lower)) return true;
  // Architectural / HABS surveys of church buildings.
  if (/^(interior|nave|narthex|iconostas)/i.test(lower)) return true;
  return false;
}

// Strict heuristic for free-text and category search results: title must
// contain an icon-genre marker. Conservative because search returns lots of
// unrelated files.
function looksLikeIcon(title: string): boolean {
  if (isObviouslyNotAnIcon(title)) return false;
  const lower = title.toLowerCase();
  return (
    lower.includes("icon") ||
    lower.includes("fresco") ||
    lower.includes("mosaic")
  );
}

// Relaxed heuristic for Wikidata P18 results: the entity's curators already
// picked this as the canonical image, so we trust it past the obvious rejects.
function looksLikeIconRelaxed(title: string): boolean {
  return !isObviouslyNotAnIcon(title);
}

// Require the saint's FIRST significant name token to appear in the title.
// (Earlier "any token" match let "Mark the Ascetic" be picked by an icon of
// "Paul/Anthony the Desert Ascetic" because "ascetic" was in the title. The
// first proper name is the most distinctive identifier.)
function matchesSaintName(title: string, name: string): boolean {
  const lowerTitle = title.toLowerCase();
  const tokens = cleanNameForSearch(name)
    .toLowerCase()
    .split(/[\s,()'-]+/)
    .filter((w) => w.length > 3 && !NAME_STOPWORDS.has(w));
  if (tokens.length === 0) return true;
  return lowerTitle.includes(tokens[0]);
}

async function findIcon(name: string): Promise<ImageInfo | null> {
  const cleaned = cleanNameForSearch(name);

  // Strategy 1: free-text search, then strict name + icon-genre filter.
  for (const q of [`${cleaned} icon`, `${cleaned} orthodox`]) {
    let results: SearchResult[];
    try {
      results = await searchCommons(q);
    } catch {
      await sleep(2000);
      continue;
    }
    const candidates = results.filter(
      (r) => looksLikeIcon(r.title) && matchesSaintName(r.title, name),
    );
    for (const candidate of candidates.slice(0, 5)) {
      const info = await imageInfo(candidate.title);
      await sleep(300);
      if (info && isAcceptable(info.license)) return info;
    }
    await sleep(400);
  }

  // Strategy 2: Commons category lookup. Many famous saints have curated
  // categories ("Category:Icons of Saint Paul") that index real icons directly,
  // so we can skip the name-token check and just need looksLikeIcon + license.
  // Try the cleaned full name first, then the first significant token alone
  // (e.g. "Paul" for "Paul, Apostle to the Nations").
  const firstToken = cleaned
    .split(/[\s,()'-]+/)
    .filter((w) => w.length > 3 && !NAME_STOPWORDS.has(w.toLowerCase()))[0];
  const categories = [
    `Category:Icons of Saint ${cleaned}`,
    `Category:Icons of ${cleaned}`,
    `Category:Saint ${cleaned}`,
    ...(firstToken && firstToken !== cleaned
      ? [
          `Category:Icons of Saint ${firstToken}`,
          `Category:Icons of ${firstToken}`,
          `Category:Saint ${firstToken}`,
        ]
      : []),
  ];
  for (const cat of categories) {
    let files: SearchResult[];
    try {
      files = await listCategoryFiles(cat);
    } catch {
      await sleep(1000);
      continue;
    }
    const candidates = files.filter((r) => looksLikeIcon(r.title));
    for (const candidate of candidates.slice(0, 5)) {
      const info = await imageInfo(candidate.title);
      await sleep(300);
      if (info && isAcceptable(info.license)) return info;
    }
    await sleep(400);
  }

  // Strategy 3: Wikidata lookup. Search Wikidata for the saint by name,
  // filter to entities whose description suggests they're a holy person, and
  // fetch their P18 (image) claim. This catches saints whose canonical icon
  // doesn't surface in Commons search/categories but is curated in Wikidata.
  let entities: WikidataEntity[];
  try {
    entities = await searchWikidata(cleaned);
  } catch {
    return null;
  }
  const holyEntities = entities.filter((e) =>
    /\b(saint|martyr|bishop|patriarch|monk|nun|apostle|prophet|holy|venerable|hieromartyr|monastic|ascetic|equal-to-the-apostles|abbot|abbess|empress|emperor|king|queen|prince|princess|orthodox)\b/i.test(
      e.description,
    ),
  );
  for (const entity of holyEntities.slice(0, 3)) {
    let filename: string | null;
    try {
      filename = await getWikidataImage(entity.id);
    } catch {
      await sleep(800);
      continue;
    }
    await sleep(300);
    if (!filename) continue;
    const fileTitle = `File:${filename}`;
    const info = await imageInfo(fileTitle);
    await sleep(300);
    if (info && isAcceptable(info.license) && looksLikeIconRelaxed(fileTitle)) {
      return info;
    }
  }
  return null;
}

type ExistingState = {
  entries: AutoEntry[];
  misses: Set<string>;
};

function readExisting(): ExistingState {
  const entries: AutoEntry[] = [];
  const misses = new Set<string>();
  if (fs.existsSync(AUTO_SOURCES_PATH)) {
    try {
      const raw = fs.readFileSync(AUTO_SOURCES_PATH, "utf8");
      // Parse the array of objects out of the TS module by reading the
      // JSON-shaped portion between the brackets. Best-effort.
      const match = raw.match(/\[\s*([\s\S]*?)\s*\];?$/m);
      if (match) {
        // Pull out each { ... personId: "X", ... } block and read personId/id.
        const blocks = match[1].match(/\{[\s\S]*?\}/g) ?? [];
        for (const block of blocks) {
          const idMatch = block.match(/id:\s*"([^"]+)"/);
          const personIdMatch = block.match(/personId:\s*"([^"]+)"/);
          const titleMatch = block.match(/wikimediaTitle:\s*"((?:[^"\\]|\\.)*)"/);
          const altMatch = block.match(/alt:\s*"((?:[^"\\]|\\.)*)"/);
          const captionMatch = block.match(/caption:\s*"((?:[^"\\]|\\.)*)"/);
          if (idMatch && personIdMatch && titleMatch && altMatch && captionMatch) {
            entries.push({
              id: idMatch[1],
              personId: personIdMatch[1],
              wikimediaTitle: titleMatch[1].replace(/\\"/g, '"'),
              alt: altMatch[1].replace(/\\"/g, '"'),
              caption: captionMatch[1].replace(/\\"/g, '"'),
            });
          }
        }
      }
    } catch (err) {
      console.warn("[auto-curate] could not re-read existing sources-auto.ts:", err);
    }
  }
  if (fs.existsSync(MISSES_PATH)) {
    try {
      const raw = fs.readFileSync(MISSES_PATH, "utf8");
      const arr = JSON.parse(raw) as string[];
      for (const id of arr) misses.add(id);
    } catch {
      // ignore
    }
  }
  return { entries, misses };
}

function writeSourcesAuto(entries: AutoEntry[]) {
  const sorted = entries.slice().sort((a, b) => a.id.localeCompare(b.id));
  const header = `// Generated by scripts/ingest/icons/auto-curate.ts. Do not hand-edit; rerun
// the script to refresh. Each entry pairs a person id with the Wikimedia
// Commons file that the auto-curator chose. fetch-wikimedia.ts reads this
// file alongside sources.ts.

import type { IconSource } from "./sources";

export const iconSourcesAuto: (IconSource & { personId: string })[] = ${JSON.stringify(
    sorted,
    null,
    2,
  )};
`;
  fs.writeFileSync(AUTO_SOURCES_PATH, header, "utf8");
}

function writeMisses(misses: Set<string>) {
  const arr = Array.from(misses).sort();
  fs.writeFileSync(MISSES_PATH, JSON.stringify(arr, null, 2) + "\n", "utf8");
}

async function main() {
  // Optional allowlist: when PATRON_IDS is set (comma-separated person ids),
  // only curate those ids. Lets a focused run target the patron set instead of
  // scanning every iconless saint in the corpus. Also re-tries ids even if
  // they're in the misses file, so a previously-missed patron gets another look.
  const allowlist = (process.env.PATRON_IDS ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  const allowSet = allowlist.length > 0 ? new Set(allowlist) : null;

  let saints = people.filter((p) => p.kind === "saint" || p.kind === "father");
  if (allowSet) {
    saints = saints.filter((p) => allowSet.has(p.id));
    console.log(`PATRON_IDS allowlist active: ${saints.length} of ${allowlist.length} requested ids matched a library person.`);
  }
  const { entries, misses } = readExisting();
  // When an allowlist is active, drop its ids from the misses set so they get
  // re-searched rather than skipped as a prior miss.
  if (allowSet) for (const id of allowSet) misses.delete(id);

  // Personas already covered: previous auto entries, known misses, or already
  // in catalog.json with an "icon-{personId}" entry (this catches both manual
  // sources.ts entries AND files imported via import-local-icons.ts, so we
  // never overwrite a hand-picked icon with an automated guess).
  const coveredPersonIds = new Set<string>();
  for (const e of entries) coveredPersonIds.add(e.personId);
  for (const id of misses) coveredPersonIds.add(id);
  const catalogPath = path.join(REPO_ROOT, "content/normalized/icons/catalog.json");
  if (fs.existsSync(catalogPath)) {
    const catalog = JSON.parse(fs.readFileSync(catalogPath, "utf8")) as {
      icons?: Array<{ id: string }>;
    };
    for (const icon of catalog.icons ?? []) {
      if (icon.id.startsWith("icon-")) {
        coveredPersonIds.add(icon.id.slice("icon-".length));
      }
    }
  }
  // Manual sources captions: also skip when a hand-curated source.ts entry
  // with a different naming convention (e.g. "icon-st-foo") covers this saint.
  const manualCaptions = new Set(
    iconSources.map((s) => (s.caption ?? "").toLowerCase()),
  );

  console.log(`Scanning ${saints.length} saints/fathers...`);
  let added = 0;
  let newMisses = 0;
  let skipped = 0;

  for (const saint of saints) {
    if (coveredPersonIds.has(saint.id)) {
      skipped++;
      continue;
    }
    // Skip if a hand-curated icon obviously covers this saint already.
    if (manualCaptions.has(saint.name.toLowerCase())) {
      skipped++;
      continue;
    }

    process.stdout.write(`  ${saint.id} ... `);
    let info: ImageInfo | null = null;
    try {
      info = await findIcon(saint.name);
    } catch (err) {
      console.log(`error: ${(err as Error).message}`);
      continue;
    }
    if (!info) {
      console.log("no PD icon found");
      misses.add(saint.id);
      newMisses++;
      writeMisses(misses);
      continue;
    }

    const cleaned = cleanNameForSearch(saint.name);
    entries.push({
      id: `icon-${saint.id}`,
      personId: saint.id,
      wikimediaTitle: info.title,
      alt: `Orthodox icon of ${cleaned}.`,
      caption: cleaned,
    });
    added++;
    console.log(`ok — ${info.title}`);
    writeSourcesAuto(entries);
    await sleep(600);
  }

  console.log(
    `\nDone. ${added} new, ${newMisses} misses, ${skipped} skipped, ${entries.length} total auto entries.`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
