// Generated by scripts/ingest/icons/auto-curate.ts. Do not hand-edit; rerun
// the script to refresh. Each entry pairs a person id with the Wikimedia
// Commons file that the auto-curator chose. fetch-wikimedia.ts reads this
// file alongside sources.ts.

import type { IconSource } from "./sources";

export const iconSourcesAuto: (IconSource & { personId: string })[] = [
  {
    "id": "icon-agatha-of-sicily",
    "personId": "agatha-of-sicily",
    "wikimediaTitle": "File:Agatha orthodox icon.jpg",
    "alt": "Orthodox icon of Agatha of Sicily.",
    "caption": "Agatha of Sicily"
  },
  {
    "id": "icon-ambrose-of-milan",
    "personId": "ambrose-of-milan",
    "wikimediaTitle": "File:Greek Icon of Saint Ambrose of Milan 1.jpg",
    "alt": "Orthodox icon of Ambrose of Milan.",
    "caption": "Ambrose of Milan"
  },
  {
    "id": "icon-ambrose-of-optina",
    "personId": "ambrose-of-optina",
    "wikimediaTitle": "File:Athonite Fresco Icon of Saint Ambrose of Milan.jpg",
    "alt": "Orthodox icon of Ambrose of Optina.",
    "caption": "Ambrose of Optina"
  },
  {
    "id": "icon-andrew-of-crete",
    "personId": "andrew-of-crete",
    "wikimediaTitle": "File:Rila Mon. - Fresco mir. icon 022 Andrew bishop of Crete.jpg",
    "alt": "Orthodox icon of Andrew of Crete.",
    "caption": "Andrew of Crete"
  },
  {
    "id": "icon-anna-the-prophetess",
    "personId": "anna-the-prophetess",
    "wikimediaTitle": "File:Prophetess Anna Icon.jpg",
    "alt": "Orthodox icon of Anna the Prophetess.",
    "caption": "Anna the Prophetess"
  },
  {
    "id": "icon-anthony-the-great",
    "personId": "anthony-the-great",
    "wikimediaTitle": "File:Cretan Icon of Saint Anthony the Great and Temptations.jpg",
    "alt": "Orthodox icon of Anthony the Great.",
    "caption": "Anthony the Great"
  },
  {
    "id": "icon-apostle-andrew",
    "personId": "apostle-andrew",
    "wikimediaTitle": "File:038 Saint Andrew Icon from Saint Paraskevi Church in Langadas.jpg",
    "alt": "Orthodox icon of Andrew the First-Called.",
    "caption": "Andrew the First-Called"
  },
  {
    "id": "icon-apostle-bartholomew",
    "personId": "apostle-bartholomew",
    "wikimediaTitle": "File:Saint Apostle Bartholomew Icon, Cretan.jpg",
    "alt": "Orthodox icon of Bartholomew the Apostle.",
    "caption": "Bartholomew the Apostle"
  },
  {
    "id": "icon-apostle-james-brother-of-lord",
    "personId": "apostle-james-brother-of-lord",
    "wikimediaTitle": "File:James the Just - icon.jpeg",
    "alt": "Orthodox icon of James the Brother of the Lord.",
    "caption": "James the Brother of the Lord"
  },
  {
    "id": "icon-apostle-john-the-theologian",
    "personId": "apostle-john-the-theologian",
    "wikimediaTitle": "File:The Death of the Holy Apostle and Evangelist John the Theologian. Icon. Greece.jpg",
    "alt": "Orthodox icon of John the Theologian and Evangelist.",
    "caption": "John the Theologian and Evangelist"
  },
  {
    "id": "icon-apostle-luke",
    "personId": "apostle-luke",
    "wikimediaTitle": "File:Saint Luke the Evangelist - icon.jpeg",
    "alt": "Orthodox icon of Luke the Evangelist.",
    "caption": "Luke the Evangelist"
  },
  {
    "id": "icon-apostle-mark",
    "personId": "apostle-mark",
    "wikimediaTitle": "File:087 Mark the Evangelist Icon from Saint Paraskevi Church in Langadas.jpg",
    "alt": "Orthodox icon of Mark the Evangelist.",
    "caption": "Mark the Evangelist"
  },
  {
    "id": "icon-apostle-matthew",
    "personId": "apostle-matthew",
    "wikimediaTitle": "File:Matthew the Evangelist - icon.jpeg",
    "alt": "Orthodox icon of Matthew the Evangelist.",
    "caption": "Matthew the Evangelist"
  },
  {
    "id": "icon-apostle-matthias",
    "personId": "apostle-matthias",
    "wikimediaTitle": "File:Apostel Matthias met bijl in omlijsting met architectuur ornamenten S. Matthias (titel op object) SS. Apostolorum et Evangelistorum Icones (serietitel), RP-P-1904-224.jpg",
    "alt": "Orthodox icon of Matthias the Apostle.",
    "caption": "Matthias the Apostle"
  },
  {
    "id": "icon-apostle-paul",
    "personId": "apostle-paul",
    "wikimediaTitle": "File:086 Paul the Apostle Icon from Saint Paraskevi Church in Langadas.jpg",
    "alt": "Orthodox icon of Paul, Apostle to the Nations.",
    "caption": "Paul, Apostle to the Nations"
  },
  {
    "id": "icon-apostle-peter",
    "personId": "apostle-peter",
    "wikimediaTitle": "File:085 Peter the Apostle Icon from Saint Paraskevi Church in Langadas.jpg",
    "alt": "Orthodox icon of Peter, Chief of the Apostles.",
    "caption": "Peter, Chief of the Apostles"
  },
  {
    "id": "icon-apostle-philip-twelve",
    "personId": "apostle-philip-twelve",
    "wikimediaTitle": "File:Apostle Philip bulgaria icon.png",
    "alt": "Orthodox icon of Philip the Apostle.",
    "caption": "Philip the Apostle"
  },
  {
    "id": "icon-apostle-simon-zealot",
    "personId": "apostle-simon-zealot",
    "wikimediaTitle": "File:Cretan Icon of the Apostle Simon.jpg",
    "alt": "Orthodox icon of Simon the Zealot.",
    "caption": "Simon the Zealot"
  },
  {
    "id": "icon-apostle-thomas",
    "personId": "apostle-thomas",
    "wikimediaTitle": "File:Apostle Thomas - Orthodox icon.jpeg",
    "alt": "Orthodox icon of Thomas the Apostle.",
    "caption": "Thomas the Apostle"
  },
  {
    "id": "icon-apostles-addai-and-mari",
    "personId": "apostles-addai-and-mari",
    "wikimediaTitle": "File:Icon of Mar Addai and Mari Apostles of the East.jpg",
    "alt": "Orthodox icon of Addai and Mari, Apostles of the East.",
    "caption": "Addai and Mari, Apostles of the East"
  },
  {
    "id": "icon-archangel-gabriel",
    "personId": "archangel-gabriel",
    "wikimediaTitle": "File:Archangel Gabriel Icon in Blue and Red.png",
    "alt": "Orthodox icon of Gabriel the Archangel.",
    "caption": "Gabriel the Archangel"
  },
  {
    "id": "icon-archangel-michael",
    "personId": "archangel-michael",
    "wikimediaTitle": "File:Unknown artist - Icon with Archangel Michael - 855 - Blackburn Museum and Art Gallery.jpg",
    "alt": "Orthodox icon of Michael the Archangel.",
    "caption": "Michael the Archangel"
  },
  {
    "id": "icon-athanasius-of-athos",
    "personId": "athanasius-of-athos",
    "wikimediaTitle": "File:104 Saint Athanasius Icon from Saint Paraskevi Church in Langadas.jpg",
    "alt": "Orthodox icon of Athanasius of Mount Athos.",
    "caption": "Athanasius of Mount Athos"
  },
  {
    "id": "icon-athanasius-the-great",
    "personId": "athanasius-the-great",
    "wikimediaTitle": "File:Saints George, Demetrius, Pantaleon, Theodores, Anthony Icon from Saint Athanasius Church in Thessaloniki 14-15 Century.jpg",
    "alt": "Orthodox icon of Athanasius the Great.",
    "caption": "Athanasius the Great"
  },
  {
    "id": "icon-barbara-great-martyr",
    "personId": "barbara-great-martyr",
    "wikimediaTitle": "File:060 Saint John Damaskinos with Saint Juliana and Saint Barbara Icon from Saint Paraskevi Church in Langadas.jpg",
    "alt": "Orthodox icon of Barbara the Great-martyr.",
    "caption": "Barbara the Great-martyr"
  },
  {
    "id": "icon-boris-and-gleb",
    "personId": "boris-and-gleb",
    "wikimediaTitle": "File:The Holy Blessed Princes and Passion-Bearers Boris and Gleb. Novgorod School of Icon Painting, 14th century.jpg",
    "alt": "Orthodox icon of Passion-Bearers Boris and Gleb.",
    "caption": "Passion-Bearers Boris and Gleb"
  },
  {
    "id": "icon-christopher-the-martyr",
    "personId": "christopher-the-martyr",
    "wikimediaTitle": "File:07 Saint Christopher and Saint Tryphon Icon in Assumption of Mary Church in Agios Vasileios.jpg",
    "alt": "Orthodox icon of Christopher.",
    "caption": "Christopher"
  },
  {
    "id": "icon-cyril-of-alexandria",
    "personId": "cyril-of-alexandria",
    "wikimediaTitle": "File:Saint Athanasius, John Eleimon and Cyril of Alexandria Icon by Veniamin of Galatista, 1833.jpg",
    "alt": "Orthodox icon of Cyril of Alexandria.",
    "caption": "Cyril of Alexandria"
  },
  {
    "id": "icon-cyril-of-jerusalem",
    "personId": "cyril-of-jerusalem",
    "wikimediaTitle": "File:Serbian Fresco Icon of Saint Cyril of Jerusalem 2.jpg",
    "alt": "Orthodox icon of Cyril of Jerusalem.",
    "caption": "Cyril of Jerusalem"
  },
  {
    "id": "icon-demetrius-of-rostov",
    "personId": "demetrius-of-rostov",
    "wikimediaTitle": "File:22 Saint Demetrius Icon from Saint Paraskevi Church in Adam.jpg",
    "alt": "Orthodox icon of Demetrius of Rostov.",
    "caption": "Demetrius of Rostov"
  },
  {
    "id": "icon-demetrius-of-thessalonica",
    "personId": "demetrius-of-thessalonica",
    "wikimediaTitle": "File:22 Saint Demetrius Icon from Saint Paraskevi Church in Adam.jpg",
    "alt": "Orthodox icon of Demetrius the Myrrh-streamer.",
    "caption": "Demetrius the Myrrh-streamer"
  },
  {
    "id": "icon-eusebius-caesarea",
    "personId": "eusebius-caesarea",
    "wikimediaTitle": "File:Eusebius of Caesarea Armenian Gospel Icon.png",
    "alt": "Orthodox icon of Eusebius of Caesarea.",
    "caption": "Eusebius of Caesarea"
  },
  {
    "id": "icon-euthymius-the-great",
    "personId": "euthymius-the-great",
    "wikimediaTitle": "File:009 Saint Euthymius Icon from Saint Paraskevi Church in Langadas.jpg",
    "alt": "Orthodox icon of Euthymius the Great.",
    "caption": "Euthymius the Great"
  },
  {
    "id": "icon-forty-martyrs-of-sebaste",
    "personId": "forty-martyrs-of-sebaste",
    "wikimediaTitle": "File:Forty Martyrs of Sebaste icon, Aleppo.jpg",
    "alt": "Orthodox icon of Forty Martyrs of Sebaste.",
    "caption": "Forty Martyrs of Sebaste"
  },
  {
    "id": "icon-george-the-trophy-bearer",
    "personId": "george-the-trophy-bearer",
    "wikimediaTitle": "File:Icon of Saint George Great Martyr.jpg",
    "alt": "Orthodox icon of George the Great-martyr.",
    "caption": "George the Great-martyr"
  },
  {
    "id": "icon-gregory-palamas",
    "personId": "gregory-palamas",
    "wikimediaTitle": "File:015 Saint Gregory Palamas Icon from Saint Paraskevi Church in Langadas.jpg",
    "alt": "Orthodox icon of Gregory Palamas.",
    "caption": "Gregory Palamas"
  },
  {
    "id": "icon-gregory-the-theologian",
    "personId": "gregory-the-theologian",
    "wikimediaTitle": "File:Gregory Palamas Fresco from Three Saints Church in Kastoria, 1401.jpg",
    "alt": "Orthodox icon of Gregory the Theologian.",
    "caption": "Gregory the Theologian"
  },
  {
    "id": "icon-herman-of-alaska",
    "personId": "herman-of-alaska",
    "wikimediaTitle": "File:INTERIOR, NAVE, LOOKING EAST AT ICONSTAS, ICONS REMOVED - Saints Sergius and Herman Russian Orthodox Churches, Old Church, Port Graham, Kenai Peninsula Borough, AK HABS AK,9-ENGB,1A-3.tif",
    "alt": "Orthodox icon of Herman of Alaska.",
    "caption": "Herman of Alaska"
  },
  {
    "id": "icon-hilarion-the-great",
    "personId": "hilarion-the-great",
    "wikimediaTitle": "File:Saints Joasaph and Hilarion Icon. Trinity Lavra of Saint Sergiy.jpg",
    "alt": "Orthodox icon of Hilarion the Great.",
    "caption": "Hilarion the Great"
  },
  {
    "id": "icon-jerome",
    "personId": "jerome",
    "wikimediaTitle": "File:Beza's Icones, contemporary portraits of reformers of religion and letters - Jerome of Prague on Page 69.jpg",
    "alt": "Orthodox icon of Jerome.",
    "caption": "Jerome"
  },
  {
    "id": "icon-joachim-and-anna",
    "personId": "joachim-and-anna",
    "wikimediaTitle": "File:Russian School - Icon with Scenes from the Life of the Virgin Mary - FA001100 - Brighton Museum ^ Art Gallery.jpg",
    "alt": "Orthodox icon of Joachim and Anna, the Holy God-bearing Ancestors.",
    "caption": "Joachim and Anna, the Holy God-bearing Ancestors"
  },
  {
    "id": "icon-john-of-damascus",
    "personId": "john-of-damascus",
    "wikimediaTitle": "File:Icon of Saint John of Damascus - Emmanouel Tzanes.jpg",
    "alt": "Orthodox icon of John of Damascus.",
    "caption": "John of Damascus"
  },
  {
    "id": "icon-justin-the-philosopher",
    "personId": "justin-the-philosopher",
    "wikimediaTitle": "File:Justin Martir in iconic Stroganoff face of the original.jpg",
    "alt": "Orthodox icon of Justin the Philosopher.",
    "caption": "Justin the Philosopher"
  },
  {
    "id": "icon-macarius-the-egyptian",
    "personId": "macarius-the-egyptian",
    "wikimediaTitle": "File:Macarius the Elder Full Body Length Icon.jpg",
    "alt": "Orthodox icon of Macarius the Egyptian.",
    "caption": "Macarius the Egyptian"
  },
  {
    "id": "icon-macarius-the-great",
    "personId": "macarius-the-great",
    "wikimediaTitle": "File:Icon of Saint Macarius the Great.jpg",
    "alt": "Orthodox icon of Macarius the Great.",
    "caption": "Macarius the Great"
  },
  {
    "id": "icon-mark-the-ascetic",
    "personId": "mark-the-ascetic",
    "wikimediaTitle": "File:029 Saint Mark Icon from Saint Paraskevi Church in Langadas.jpg",
    "alt": "Orthodox icon of Mark the Ascetic.",
    "caption": "Mark the Ascetic"
  },
  {
    "id": "icon-martyr-irene",
    "personId": "martyr-irene",
    "wikimediaTitle": "File:Rila Mon. - Fresco mir. icon 021 Irene of Macedonia.jpg",
    "alt": "Orthodox icon of Irene of Macedonia.",
    "caption": "Irene of Macedonia"
  },
  {
    "id": "icon-martyr-marina",
    "personId": "martyr-marina",
    "wikimediaTitle": "File:Cretan Icon of Saint Marina from the Saint Marina Monastery in Andros.jpg",
    "alt": "Orthodox icon of Marina of Antioch in Pisidia.",
    "caption": "Marina of Antioch in Pisidia"
  },
  {
    "id": "icon-martyr-mercurius",
    "personId": "martyr-mercurius",
    "wikimediaTitle": "File:02 Saint Mercurius and Saint Catherine Icon in Assumption of Mary Church in Agios Vasileios.jpg",
    "alt": "Orthodox icon of Mercurius.",
    "caption": "Mercurius"
  },
  {
    "id": "icon-mary-of-egypt",
    "personId": "mary-of-egypt",
    "wikimediaTitle": "File:Icon of Mary of Egypt (Mstera, 19th c.).jpg",
    "alt": "Orthodox icon of Mary of Egypt.",
    "caption": "Mary of Egypt"
  },
  {
    "id": "icon-nektarios-of-aegina",
    "personId": "nektarios-of-aegina",
    "wikimediaTitle": "File:Saint Nektarios of Aegina Icon.jpg",
    "alt": "Orthodox icon of Nektarios of Aegina.",
    "caption": "Nektarios of Aegina"
  },
  {
    "id": "icon-nicholas-of-myra",
    "personId": "nicholas-of-myra",
    "wikimediaTitle": "File:Russian icon of 'St. Nicholas the Wonderworker' (half-length), 17th century .JPG",
    "alt": "Orthodox icon of Nicholas the Wonderworker.",
    "caption": "Nicholas the Wonderworker"
  },
  {
    "id": "icon-paraskeva-friday",
    "personId": "paraskeva-friday",
    "wikimediaTitle": "File:St Paraskeva Pezovo 1898 Icon Yosif Radev.jpg",
    "alt": "Orthodox icon of Paraskeva.",
    "caption": "Paraskeva"
  },
  {
    "id": "icon-peter-of-moscow",
    "personId": "peter-of-moscow",
    "wikimediaTitle": "File:Icon of Saints Peter the Metropolitan, Leonty of Rostov, and Theodosius of the Caves. Novgorod School of Iconography, late 15th – early 16th century. Tretyakov Gallery, Russia.jpg",
    "alt": "Orthodox icon of Peter, Metropolitan of Moscow.",
    "caption": "Peter, Metropolitan of Moscow"
  },
  {
    "id": "icon-philip-of-moscow",
    "personId": "philip-of-moscow",
    "wikimediaTitle": "File:014 Saint Philip Icon from Saint Paraskevi Church in Langadas.jpg",
    "alt": "Orthodox icon of Philip the Confessor, Metropolitan of Moscow.",
    "caption": "Philip the Confessor, Metropolitan of Moscow"
  },
  {
    "id": "icon-prophet-daniel",
    "personId": "prophet-daniel",
    "wikimediaTitle": "File:Icon of the Prophet Daniel and the Three Holy Youths.jpg",
    "alt": "Orthodox icon of Daniel the Prophet and the Three Holy Youths.",
    "caption": "Daniel the Prophet and the Three Holy Youths"
  },
  {
    "id": "icon-prophet-david-king",
    "personId": "prophet-david-king",
    "wikimediaTitle": "File:Amgueddfa Cymru - Braslun ar gyfer mosaig Dewi Sant - Sketch for the St. David mosaic - 137895.jpeg",
    "alt": "Orthodox icon of David the King and Prophet.",
    "caption": "David the King and Prophet"
  },
  {
    "id": "icon-prophet-elisha",
    "personId": "prophet-elisha",
    "wikimediaTitle": "File:Kirillo-Belozersky iconostasis 07. Elisha, Zechariah, Joel.jpg",
    "alt": "Orthodox icon of Elisha the Prophet.",
    "caption": "Elisha the Prophet"
  },
  {
    "id": "icon-prophet-ezekiel",
    "personId": "prophet-ezekiel",
    "wikimediaTitle": "File:Ezekiel-icon.jpg",
    "alt": "Orthodox icon of Ezekiel the Prophet.",
    "caption": "Ezekiel the Prophet"
  },
  {
    "id": "icon-prophet-isaiah",
    "personId": "prophet-isaiah",
    "wikimediaTitle": "File:Icon of Isaiah (19th c, priv.coll.).jpg",
    "alt": "Orthodox icon of Isaiah the Prophet.",
    "caption": "Isaiah the Prophet"
  },
  {
    "id": "icon-prophet-jeremiah",
    "personId": "prophet-jeremiah",
    "wikimediaTitle": "File:Prophet Jeremiah Icon.tif",
    "alt": "Orthodox icon of Jeremiah the Prophet.",
    "caption": "Jeremiah the Prophet"
  },
  {
    "id": "icon-prophet-samuel",
    "personId": "prophet-samuel",
    "wikimediaTitle": "File:Prophet Samuel, Russian Icon, private gallery, London.jpg",
    "alt": "Orthodox icon of Samuel the Prophet.",
    "caption": "Samuel the Prophet"
  },
  {
    "id": "icon-protomartyr-stephen",
    "personId": "protomartyr-stephen",
    "wikimediaTitle": "File:012 Saint Stephen Icon from Saint Paraskevi Church in Langadas.jpg",
    "alt": "Orthodox icon of Stephen the Protomartyr and Archdeacon.",
    "caption": "Stephen the Protomartyr and Archdeacon"
  },
  {
    "id": "icon-sabbas-the-sanctified",
    "personId": "sabbas-the-sanctified",
    "wikimediaTitle": "File:065 Saint Stylianos and Saint Sabbas Icon from Saint Paraskevi Church in Langadas.jpg",
    "alt": "Orthodox icon of Sabbas the Sanctified.",
    "caption": "Sabbas the Sanctified"
  },
  {
    "id": "icon-sava-of-serbia",
    "personId": "sava-of-serbia",
    "wikimediaTitle": "File:Saint Sava, fresco from Mileševa.jpg",
    "alt": "Orthodox icon of Sava, First Archbishop of Serbia.",
    "caption": "Sava, First Archbishop of Serbia"
  },
  {
    "id": "icon-sergius-of-radonezh",
    "personId": "sergius-of-radonezh",
    "wikimediaTitle": "File:Sergius of Radonezh vita icon (17 c., Yaroslavl museum) - detail 01.jpg",
    "alt": "Orthodox icon of Sergius of Radonezh.",
    "caption": "Sergius of Radonezh"
  },
  {
    "id": "icon-silouan-the-athonite",
    "personId": "silouan-the-athonite",
    "wikimediaTitle": "File:Silouanicon.jpg",
    "alt": "Orthodox icon of Silouan the Athonite.",
    "caption": "Silouan the Athonite"
  },
  {
    "id": "icon-sophia-and-three-daughters",
    "personId": "sophia-and-three-daughters",
    "wikimediaTitle": "File:Icon of Sophia, and her three daughters.jpg",
    "alt": "Orthodox icon of Sophia and her Daughters Faith, Hope, and Love.",
    "caption": "Sophia and her Daughters Faith, Hope, and Love"
  },
  {
    "id": "icon-symeon-the-new-theologian",
    "personId": "symeon-the-new-theologian",
    "wikimediaTitle": "File:SYMEON-icon.jpg",
    "alt": "Orthodox icon of Symeon the New Theologian.",
    "caption": "Symeon the New Theologian"
  },
  {
    "id": "icon-tatiana-of-rome",
    "personId": "tatiana-of-rome",
    "wikimediaTitle": "File:BabushinIcons1681.jpg",
    "alt": "Orthodox icon of Tatiana of Rome.",
    "caption": "Tatiana of Rome"
  },
  {
    "id": "icon-theodore-the-general",
    "personId": "theodore-the-general",
    "wikimediaTitle": "File:Theodore Stratelates. Iprari church fresco. 1096.jpg",
    "alt": "Orthodox icon of Theodore the General (Stratelates).",
    "caption": "Theodore the General (Stratelates)"
  },
  {
    "id": "icon-theodosius-of-the-caves",
    "personId": "theodosius-of-the-caves",
    "wikimediaTitle": "File:Icon of Saints Peter the Metropolitan, Leonty of Rostov, and Theodosius of the Caves. Novgorod School of Iconography, late 15th – early 16th century. Tretyakov Gallery, Russia.jpg",
    "alt": "Orthodox icon of Theodosius of the Caves of Kiev.",
    "caption": "Theodosius of the Caves of Kiev"
  },
  {
    "id": "icon-tryphon-the-martyr",
    "personId": "tryphon-the-martyr",
    "wikimediaTitle": "File:068 Saint Tryphon Icon from Saint Paraskevi Church in Langadas.jpg",
    "alt": "Orthodox icon of Tryphon of Lampsacus.",
    "caption": "Tryphon of Lampsacus"
  }
];
