// Generated by scripts/ingest/icons/auto-curate.ts, then hand-pruned to drop
// false matches where the auto-curator picked a famous same-named saint's icon
// (e.g. the Archangel Raphael for St. Raphael of Brooklyn, the Apostle Peter
// for Peter the Aleut). The dropped person ids were moved to
// sources-auto-misses.json so future runs treat them as "needs a manual icon."
// fetch-wikimedia.ts reads this file alongside sources.ts.

import type { IconSource } from "./sources";

export const iconSourcesAuto: (IconSource & { personId: string })[] = [
  {
    "id": "icon-aidan-of-lindisfarne",
    "personId": "aidan-of-lindisfarne",
    "wikimediaTitle": "File:Saint Aidan.jpg",
    "alt": "Orthodox icon of Aidan of Lindisfarne.",
    "caption": "Aidan of Lindisfarne"
  },
  {
    "id": "icon-alexander-hotovitzky",
    "personId": "alexander-hotovitzky",
    "wikimediaTitle": "File:Alexander Hotovitsky fresco.jpg",
    "alt": "Orthodox icon of Alexander Hotovitzky.",
    "caption": "Alexander Hotovitzky"
  },
  {
    "id": "icon-alexander-nevsky",
    "personId": "alexander-nevsky",
    "wikimediaTitle": "File:Icon of sacred prince Alexander Nevsky.jpg",
    "alt": "Orthodox icon of Prince Alexander Nevsky.",
    "caption": "Prince Alexander Nevsky"
  },
  {
    "id": "icon-alexander-svirsky",
    "personId": "alexander-svirsky",
    "wikimediaTitle": "File:Icon of St Alexander of Svir.jpg",
    "alt": "Orthodox icon of Alexander of Svir.",
    "caption": "Alexander of Svir"
  },
  {
    "id": "icon-arsenios-the-cappadocian",
    "personId": "arsenios-the-cappadocian",
    "wikimediaTitle": "File:Arsenios the Cappadocian († 1924).jpg",
    "alt": "Orthodox icon of Arsenios the Cappadocian.",
    "caption": "Arsenios the Cappadocian"
  },
  {
    "id": "icon-brigid-of-kildare",
    "personId": "brigid-of-kildare",
    "wikimediaTitle": "File:Brigid of Kildare, Vitrall, 1903 (Macon, Georgia, St. Joseph Parish Church).jpg",
    "alt": "Orthodox icon of Brigid of Kildare.",
    "caption": "Brigid of Kildare"
  },
  {
    "id": "icon-calinic-of-cernica",
    "personId": "calinic-of-cernica",
    "wikimediaTitle": "File:RmVl Calinic icon.PNG",
    "alt": "Orthodox icon of Calinic of Cernica.",
    "caption": "Calinic of Cernica"
  },
  {
    "id": "icon-cyprian-and-justina",
    "personId": "cyprian-and-justina",
    "wikimediaTitle": "File:Icon in sts. Cyprian and Justina cathedral.jpg",
    "alt": "Orthodox icon of Cyprian and Justina.",
    "caption": "Cyprian and Justina"
  },
  {
    "id": "icon-david-of-wales",
    "personId": "david-of-wales",
    "wikimediaTitle": "File:Amgueddfa Cymru - Braslun ar gyfer mosaig Dewi Sant - Sketch for the St. David mosaic - 137895.jpeg",
    "alt": "Orthodox icon of David (Dewi) of Wales.",
    "caption": "David (Dewi) of Wales"
  },
  {
    "id": "icon-david-the-builder",
    "personId": "david-the-builder",
    "wikimediaTitle": "File:Icon of Saint George and the Georgian King David IV. Sinai, Monastery of Saint Catherine.jpg",
    "alt": "Orthodox icon of King David the Builder.",
    "caption": "King David the Builder"
  },
  {
    "id": "icon-dionysios-of-zakynthos",
    "personId": "dionysios-of-zakynthos",
    "wikimediaTitle": "File:Saint Dionysius of Zante.jpg",
    "alt": "Orthodox icon of Dionysios of Zakynthos.",
    "caption": "Dionysios of Zakynthos"
  },
  {
    "id": "icon-edward-the-martyr",
    "personId": "edward-the-martyr",
    "wikimediaTitle": "File:Edward the Martyr - MS Royal 14 B VI.jpg",
    "alt": "Orthodox icon of King Edward the Martyr.",
    "caption": "King Edward the Martyr"
  },
  {
    "id": "icon-ephraim-of-katounakia",
    "personId": "ephraim-of-katounakia",
    "wikimediaTitle": "File:ΕΦΡΑΙΜ ΚΑΤΟΥΝΑΚΙΩΤΗΣ.jpg",
    "alt": "Orthodox icon of Ephraim of Katounakia.",
    "caption": "Ephraim of Katounakia"
  },
  {
    "id": "icon-genevieve-of-paris",
    "personId": "genevieve-of-paris",
    "wikimediaTitle": "File:Ste genevieve st etienne.jpg",
    "alt": "Orthodox icon of Genevieve of Paris.",
    "caption": "Genevieve of Paris"
  },
  {
    "id": "icon-job-of-pochaev",
    "personId": "job-of-pochaev",
    "wikimediaTitle": "File:Venerable Job of Pochaev in prayer before the Pochaev Icon of the Mother of God. Icon. (Pochaev Lavra).jpg",
    "alt": "Orthodox icon of Job of Pochaev.",
    "caption": "Job of Pochaev"
  },
  {
    "id": "icon-john-kochurov",
    "personId": "john-kochurov",
    "wikimediaTitle": "File:St. John Kochurov.jpeg",
    "alt": "Orthodox icon of John Kochurov.",
    "caption": "John Kochurov"
  },
  {
    "id": "icon-joseph-the-hesychast",
    "personId": "joseph-the-hesychast",
    "wikimediaTitle": "File:FullBodyIconOfElderJoseph.jpg",
    "alt": "Orthodox icon of Joseph the Hesychast.",
    "caption": "Joseph the Hesychast"
  },
  {
    "id": "icon-juvenaly-of-alaska",
    "personId": "juvenaly-of-alaska",
    "wikimediaTitle": "File:Juvenaly of Alaska.JPG",
    "alt": "Orthodox icon of Juvenaly of Alaska.",
    "caption": "Juvenaly of Alaska"
  },
  {
    "id": "icon-matrona-of-moscow",
    "personId": "matrona-of-moscow",
    "wikimediaTitle": "File:Icons of Matrona of Moscow (Wittgenstein)-6.jpg",
    "alt": "Orthodox icon of Matrona of Moscow.",
    "caption": "Matrona of Moscow"
  },
  {
    "id": "icon-nilus-of-sora",
    "personId": "nilus-of-sora",
    "wikimediaTitle": "File:Nilsora.jpg",
    "alt": "Orthodox icon of Nilus of Sora.",
    "caption": "Nilus of Sora"
  },
  {
    "id": "icon-patrick-of-ireland",
    "personId": "patrick-of-ireland",
    "wikimediaTitle": "File:Icon of Saint Patrick, Christ the Saviour Church.jpg",
    "alt": "Orthodox icon of Patrick, Enlightener of Ireland.",
    "caption": "Patrick, Enlightener of Ireland"
  },
  {
    "id": "icon-scholastica",
    "personId": "scholastica",
    "wikimediaTitle": "File:SantaScolastica Montecassino.jpg",
    "alt": "Orthodox icon of Scholastica.",
    "caption": "Scholastica"
  },
  {
    "id": "icon-sebastian-dabovich",
    "personId": "sebastian-dabovich",
    "wikimediaTitle": "File:Seattle - Our Lady of the Lake - interior 41 - icon of St. Sebastian.jpg",
    "alt": "Orthodox icon of Sebastian (Dabovich) of Jackson.",
    "caption": "Sebastian (Dabovich) of Jackson"
  }
];
