import {
  type AugustineTreatiseConfig,
  type CommentaryBundleV2,
  buildAugustineTreatiseBundle,
} from "./augustine-treatise";

// Catalog of Augustine's library-reading treatises that ship as flat New Advent
// pages (self-contained or short multi-subpage). Each becomes its own bundle
// at content/generated/commentary/<slug>.json so the library page renders the
// work independently.
//
// Custom-parser works (handled outside this batch):
//   1102 Letters — per-letter recipient metadata extracted from the index TOC
//   1602 Harmony of the Gospels — 153 paragraph-level subpages collapsed into
//        4 books
//   1603 Sermons on Selected Lessons — per-sermon pericope → verse commentary
//   1701/1702/1801 — already shipped as verse commentary
//   1101/1201/1301/1601 — already shipped as their own parsers

const TREATISES: AugustineTreatiseConfig[] = [
  // ── NPNF I, Vol. 2 — Doctrinal ────────────────────────────────────────────
  {
    naId: "1202",
    slug: "augustine-christian-doctrine",
    title: "On Christian Doctrine",
    shortTitle: "On Christian Doctrine",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "c. 397–426",
    summary:
      "A four-book handbook on how to interpret and teach Scripture — the first three books on hermeneutics (signs, things, ambiguity, figurative reading), the fourth on Christian rhetoric and preaching. Foundational text in patristic exegesis.",
    npnfSeries: "First",
    npnfVolume: 2,
    npnfYear: 1887,
    translator: "J.F. Shaw",
  },

  // ── NPNF I, Vol. 3 — Short doctrinal treatises ────────────────────────────
  {
    naId: "1302",
    slug: "augustine-enchiridion",
    title: "The Enchiridion on Faith, Hope, and Love",
    shortTitle: "Enchiridion",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "c. 421",
    summary:
      "Augustine's compact handbook of Christian doctrine, structured around the three theological virtues — faith (the Creed), hope (the Lord's Prayer), and love (the moral life). Written for the layman Laurentius as a concise statement of orthodox faith.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "J.F. Shaw",
  },
  {
    naId: "1303",
    slug: "augustine-catechising-uninstructed",
    title: "On the Catechising of the Uninstructed",
    shortTitle: "Catechising the Uninstructed",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "c. 405",
    summary:
      "A pastoral letter to the deacon Deogratias on how to catechize beginners — diagnosing why catechists grow weary and offering a sample first lesson tracing salvation history from creation to the Church.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "S.D.F. Salmond",
  },
  {
    naId: "1304",
    slug: "augustine-faith-and-creed",
    title: "On Faith and the Creed",
    shortTitle: "On Faith and the Creed",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "393",
    summary:
      "A sermon delivered before the African bishops at Hippo expounding the articles of the Creed — written in Augustine's first year of priesthood.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "S.D.F. Salmond",
  },
  {
    naId: "1305",
    slug: "augustine-faith-things-not-seen",
    title: "Concerning Faith of Things Not Seen",
    shortTitle: "Faith of Things Not Seen",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "c. 400",
    summary:
      "A short apologetic treatise arguing that faith in unseen realities is not credulity but rational confidence — the same kind of confidence the soul places in invisible loves, intentions, and the testimony of trusted witnesses.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "C.L. Cornish",
  },
  {
    naId: "1306",
    slug: "augustine-profit-of-believing",
    title: "On the Profit of Believing",
    shortTitle: "Profit of Believing",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "391",
    summary:
      "Addressed to Augustine's Manichaean friend Honoratus, arguing that authority and faith are reasonable starting points for the spiritual life and that Manichaean rationalism is itself a kind of credulity.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "C.L. Cornish",
  },
  {
    naId: "1307",
    slug: "augustine-creed-sermon-catechumens",
    title: "On the Creed: A Sermon to Catechumens",
    shortTitle: "Sermon to Catechumens",
    workType: "homily",
    lengthLabel: "short",
    eraLabel: "c. 393–400",
    summary:
      "A short catechetical sermon delivered to those preparing for baptism, walking line by line through the articles of the Creed.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "H. Browne",
  },
  {
    naId: "1308",
    slug: "augustine-continence",
    title: "On Continence",
    shortTitle: "On Continence",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "c. 395",
    summary:
      "A treatise on the virtue of continence as the interior mastery of the will, not merely the renunciation of marriage — framing continence within the wider Christian moral life.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "C.L. Cornish",
  },
  {
    naId: "1309",
    slug: "augustine-good-of-marriage",
    title: "On the Good of Marriage",
    shortTitle: "Good of Marriage",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "401",
    summary:
      "Augustine's defense of marriage as a true good — naming the three goods of marriage as offspring, fidelity, and sacrament — while still ranking continence higher in the order of virtues.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "C.L. Cornish",
  },
  {
    naId: "1310",
    slug: "augustine-holy-virginity",
    title: "On Holy Virginity",
    shortTitle: "Holy Virginity",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "401",
    summary:
      "Companion piece to On the Good of Marriage, articulating virginity as a higher gift while warning against pride and contempt for those in the married estate.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "C.L. Cornish",
  },
  {
    naId: "1311",
    slug: "augustine-good-of-widowhood",
    title: "On the Good of Widowhood",
    shortTitle: "Good of Widowhood",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "414",
    summary:
      "A pastoral letter to the noblewoman Juliana on Christian widowhood — the dignity of perseverance, the prudent care of household and children, and the discipline of the affections.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "C.L. Cornish",
  },
  {
    naId: "1312",
    slug: "augustine-on-lying",
    title: "On Lying",
    shortTitle: "On Lying",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "c. 395",
    summary:
      "Augustine's first treatise on the morality of lying, distinguishing eight kinds and arguing the absolute prohibition — even to save a life.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "H. Browne",
  },
  {
    naId: "1313",
    slug: "augustine-against-lying",
    title: "To Consentius: Against Lying",
    shortTitle: "Against Lying",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "c. 420",
    summary:
      "Companion piece to On Lying, written against Spanish Priscillianists who held that the faithful might use deception to root out heresy.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "H. Browne",
  },
  {
    naId: "1314",
    slug: "augustine-work-of-monks",
    title: "On the Work of Monks",
    shortTitle: "Work of Monks",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "c. 401",
    summary:
      "Augustine's response to monks at Carthage who refused manual labor on supposed scriptural grounds, arguing that work is integral to the monastic life and that idleness is not contemplation.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "H. Browne",
  },
  {
    naId: "1315",
    slug: "augustine-patience",
    title: "On Patience",
    shortTitle: "On Patience",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "c. 418",
    summary:
      "A short treatise on patience as the soul's endurance of evils for the sake of the good — true patience grounded in love of God, not Stoic indifference.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "H. Browne",
  },
  {
    naId: "1316",
    slug: "augustine-care-for-the-dead",
    title: "On Care to be Had for the Dead",
    shortTitle: "Care for the Dead",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "c. 421",
    summary:
      "Written to Paulinus of Nola on whether burial near the bodies of martyrs benefits the dead. Augustine concludes that the prayers and almsgiving of the living are the real spiritual aid, not the place of burial.",
    npnfSeries: "First",
    npnfVolume: 3,
    npnfYear: 1887,
    translator: "H. Browne",
  },

  // ── NPNF I, Vol. 4 — Anti-Manichaean & Anti-Donatist ──────────────────────
  {
    naId: "1401",
    slug: "augustine-morals-catholic-church",
    title: "On the Morals of the Catholic Church",
    shortTitle: "Morals of the Catholic Church",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "388",
    summary:
      "One of Augustine's earliest anti-Manichaean writings, contrasting Catholic moral life with Manichaean dualism. Argues that the good of the soul is the love of God known through the four cardinal virtues understood as forms of love.",
    npnfSeries: "First",
    npnfVolume: 4,
    npnfYear: 1887,
    translator: "Richard Stothert",
  },
  {
    naId: "1402",
    slug: "augustine-morals-manichaeans",
    title: "On the Morals of the Manichaeans",
    shortTitle: "Morals of the Manichaeans",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "388",
    summary:
      "Companion polemic to On the Morals of the Catholic Church, dissecting the Manichaean elect's ethical pretensions and their cosmological dualism.",
    npnfSeries: "First",
    npnfVolume: 4,
    npnfYear: 1887,
    translator: "Richard Stothert",
  },
  {
    naId: "1403",
    slug: "augustine-two-souls",
    title: "On Two Souls, Against the Manichaeans",
    shortTitle: "On Two Souls",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "391",
    summary:
      "Refutes the Manichaean doctrine that humans possess two souls — one good and one evil — arguing instead that all souls are created good and that evil is a privation of the will.",
    npnfSeries: "First",
    npnfVolume: 4,
    npnfYear: 1887,
    translator: "Albert H. Newman",
  },
  {
    naId: "1404",
    slug: "augustine-acts-against-fortunatus",
    title: "Acts or Disputation Against Fortunatus the Manichaean",
    shortTitle: "Against Fortunatus",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "392",
    summary:
      "Transcript of a public two-day debate between Augustine and the Manichaean presbyter Fortunatus at Hippo, during which Fortunatus famously withdrew defeated.",
    npnfSeries: "First",
    npnfVolume: 4,
    npnfYear: 1887,
    translator: "Albert H. Newman",
  },
  {
    naId: "1405",
    slug: "augustine-against-epistle-manichaeus",
    title: "Against the Epistle of Manichaeus Called Fundamental",
    shortTitle: "Against the Epistle of Manichaeus",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "396–397",
    summary:
      "A measured refutation of the foundational epistle of Mani, expressing pastoral hope for the Manichaeans even as it dismantles their cosmology and Christology.",
    npnfSeries: "First",
    npnfVolume: 4,
    npnfYear: 1887,
    translator: "Richard Stothert",
  },
  {
    naId: "1407",
    slug: "augustine-nature-of-good",
    title: "Concerning the Nature of Good, Against the Manichaeans",
    shortTitle: "Nature of Good",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "c. 399",
    summary:
      "A late summary of Augustine's anti-Manichaean metaphysics: God is the supreme good, all natures are good by participation, and evil is the corruption of measure, form, and order.",
    npnfSeries: "First",
    npnfVolume: 4,
    npnfYear: 1887,
    translator: "Albert H. Newman",
  },
  {
    naId: "1408",
    slug: "augustine-on-baptism",
    title: "On Baptism, Against the Donatists",
    shortTitle: "On Baptism",
    workType: "treatise",
    lengthLabel: "long",
    eraLabel: "c. 400",
    summary:
      "Seven books refuting the Donatist insistence on rebaptism, arguing that the sacrament's validity depends on Christ's institution, not the moral character of the minister — Augustine's mature ecclesiology of catholic unity.",
    npnfSeries: "First",
    npnfVolume: 4,
    npnfYear: 1887,
    translator: "J.R. King",
  },
  {
    naId: "1409",
    slug: "augustine-answer-petilian",
    title: "Answer to Letters of Petilian, Bishop of Cirta",
    shortTitle: "Answer to Petilian",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "c. 401",
    summary:
      "A three-book point-by-point refutation of the Donatist bishop Petilian's pastoral letters — a sustained anti-Donatist polemic on the catholicity of the Church.",
    npnfSeries: "First",
    npnfVolume: 4,
    npnfYear: 1887,
    translator: "J.R. King",
  },

  // ── NPNF I, Vol. 5 — Anti-Pelagian ────────────────────────────────────────
  {
    naId: "1501",
    slug: "augustine-merits-remission",
    title: "On the Merits and Remission of Sin, and on Infant Baptism",
    shortTitle: "Merits and Remission",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "412",
    summary:
      "Augustine's first major anti-Pelagian work, written to the tribune Marcellinus. Argues that infants are baptized for the remission of original sin inherited from Adam, refuting Pelagian denials of inherited guilt.",
    npnfSeries: "First",
    npnfVolume: 5,
    npnfYear: 1887,
    translator: "Peter Holmes",
  },
  {
    naId: "1502",
    slug: "augustine-spirit-and-letter",
    title: "On the Spirit and the Letter",
    shortTitle: "Spirit and the Letter",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "412",
    summary:
      "A meditation on 2 Cor 3:6 (\"the letter killeth, but the spirit giveth life\"). Foundational for Augustine's doctrine of grace — the law shows sin but cannot heal; only the Spirit poured into hearts can fulfill the law.",
    npnfSeries: "First",
    npnfVolume: 5,
    npnfYear: 1887,
    translator: "Peter Holmes",
  },
  {
    naId: "1503",
    slug: "augustine-nature-and-grace",
    title: "On Nature and Grace",
    shortTitle: "Nature and Grace",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "415",
    summary:
      "Written against Pelagius's book On Nature. Augustine concedes the goodness of human nature as created but argues that fallen nature cannot be healed without grace — the same grace Pelagius made into nature itself.",
    npnfSeries: "First",
    npnfVolume: 5,
    npnfYear: 1887,
    translator: "Peter Holmes",
  },
  {
    naId: "1504",
    slug: "augustine-perfection-righteousness",
    title: "On Man's Perfection in Righteousness",
    shortTitle: "Perfection in Righteousness",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "415",
    summary:
      "Augustine's careful response to a Pelagian set of propositions asserting that a person can live without sin. Distinguishes the ideal of perfect righteousness from its actual possibility in this life.",
    npnfSeries: "First",
    npnfVolume: 5,
    npnfYear: 1887,
    translator: "Peter Holmes",
  },
  {
    naId: "1505",
    slug: "augustine-proceedings-pelagius",
    title: "On the Proceedings of Pelagius",
    shortTitle: "Proceedings of Pelagius",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "417",
    summary:
      "Augustine's account of the synod of Diospolis (415), at which Pelagius had been acquitted. Shows how Pelagius dissembled his actual teaching and answered orthodox questions with deliberate ambiguity.",
    npnfSeries: "First",
    npnfVolume: 5,
    npnfYear: 1887,
    translator: "Peter Holmes",
  },
  {
    naId: "1506",
    slug: "augustine-grace-of-christ",
    title: "On the Grace of Christ and on Original Sin",
    shortTitle: "Grace of Christ and Original Sin",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "418",
    summary:
      "Two-book treatise written after the Council of Carthage (418). Book I demonstrates that Pelagius's \"grace\" reduces to nature plus teaching; Book II defends the doctrine of original sin transmitted from Adam.",
    npnfSeries: "First",
    npnfVolume: 5,
    npnfYear: 1887,
    translator: "Peter Holmes",
  },
  {
    naId: "1507",
    slug: "augustine-marriage-and-concupiscence",
    title: "On Marriage and Concupiscence",
    shortTitle: "Marriage and Concupiscence",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "419–420",
    summary:
      "Against Julian of Eclanum's defense of Pelagianism. Distinguishes the good of marriage (institutive of children, fidelity, and sacrament) from the disordered concupiscence that touches even lawful unions after the Fall.",
    npnfSeries: "First",
    npnfVolume: 5,
    npnfYear: 1887,
    translator: "Peter Holmes",
  },
  {
    naId: "1508",
    slug: "augustine-soul-and-origin",
    title: "On the Soul and its Origin",
    shortTitle: "Soul and its Origin",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "419–420",
    summary:
      "Four books addressed to the young Spanish priest Vincentius Victor, who had published a hasty treatise on the soul. Augustine rebukes him for theological overreach and clarifies what can and cannot be known about the soul's origin.",
    npnfSeries: "First",
    npnfVolume: 5,
    npnfYear: 1887,
    translator: "Peter Holmes",
  },
  {
    naId: "1509",
    slug: "augustine-against-two-letters-pelagians",
    title: "Against Two Letters of the Pelagians",
    shortTitle: "Against Two Letters of the Pelagians",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "420",
    summary:
      "Four books addressed to Pope Boniface, refuting Pelagian letters circulating in Rome. Sustained polemic on grace, free will, and the unity of the Catholic Church in opposing the new heresy.",
    npnfSeries: "First",
    npnfVolume: 5,
    npnfYear: 1887,
    translator: "Peter Holmes",
  },
  {
    naId: "1510",
    slug: "augustine-grace-and-free-will",
    title: "On Grace and Free Will",
    shortTitle: "Grace and Free Will",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "426",
    summary:
      "A short late treatise to the monks of Hadrumetum harmonizing free will and grace — both true, but free will itself a gift of grace.",
    npnfSeries: "First",
    npnfVolume: 5,
    npnfYear: 1887,
    translator: "Peter Holmes",
  },
  {
    naId: "1512",
    slug: "augustine-predestination-of-saints",
    title: "On the Predestination of the Saints",
    shortTitle: "Predestination of the Saints",
    workType: "treatise",
    lengthLabel: "medium",
    eraLabel: "428–429",
    summary:
      "Two-book treatise to Prosper and Hilary against the semi-Pelagians of southern Gaul who admitted grace but assigned the beginning of faith to free will. Augustine argues that even the beginning of faith is itself the gift of God.",
    npnfSeries: "First",
    npnfVolume: 5,
    npnfYear: 1887,
    translator: "Peter Holmes",
  },
  {
    naId: "1513",
    slug: "augustine-rebuke-and-grace",
    title: "On Rebuke and Grace",
    shortTitle: "Rebuke and Grace",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "426",
    summary:
      "Companion to On Grace and Free Will, addressed to the same monks. Defends the propriety of rebuking sinners even while affirming that perseverance is a gift; rebuke is a means by which God works the gift of perseverance.",
    npnfSeries: "First",
    npnfVolume: 5,
    npnfYear: 1887,
    translator: "Peter Holmes",
  },

  // ── NPNF I, Vol. 4 — Reply to Faustus the Manichaean ─────────────────────
  {
    naId: "1406",
    slug: "augustine-reply-faustus",
    title: "Reply to Faustus the Manichaean",
    shortTitle: "Reply to Faustus",
    workType: "treatise",
    lengthLabel: "long",
    eraLabel: "c. 397–400",
    summary:
      "Augustine's largest anti-Manichaean polemic — thirty-three books refuting Faustus the Manichaean point by point. Defends the unity of Old and New Testaments, the goodness of created matter, and the figural reading of patriarchal narratives against Manichaean rejection of the Hebrew Scriptures.",
    npnfSeries: "First",
    npnfVolume: 4,
    npnfYear: 1887,
    translator: "Richard Stothert",
  },

  // ── NPNF I, Vol. 7 — Soliloquies ──────────────────────────────────────────
  {
    naId: "1703",
    slug: "augustine-soliloquies",
    title: "Soliloquies",
    shortTitle: "Soliloquies",
    workType: "treatise",
    lengthLabel: "short",
    eraLabel: "386–387",
    summary:
      "A philosophical dialogue between Augustine and Reason, written at Cassiciacum shortly before his baptism. Two books on the nature of the soul and on the soul's path to knowledge of God and the truth.",
    npnfSeries: "First",
    npnfVolume: 7,
    npnfYear: 1888,
    translator: "C.C. Starbuck",
  },
];

export function parseAugustineTreatises(args: {
  rawDir: string;
}): CommentaryBundleV2[] {
  return TREATISES.map((config) =>
    buildAugustineTreatiseBundle({ rawDir: args.rawDir, config }),
  );
}

export { TREATISES };
